### ISSUE TITLE
min-entropy not defined or explained

### ISSUE THREAD

**Issue by JohnDenker** [usnistgov/SP800-90B_EntropyAssessment#10]
### Observed behavior:
In the user guide and in the code, the term min-entropy is widely used.  In some circles this is "standard terminology", but not everyone who uses this package is aware of that.  Some who know the definition of "min" and the definition of "entropy" are not aware that "min-entropy" is a two-word idiomatic expression.  This is demonstrably a source of confusion.

### Suggestion 1:
In the user guide, say a few words about the definitions.  One possibility is to contrast the various
Rényi functionals H_α for various values of α:
```
H_0 = log Σ 1             = Hartley functional   = log multiplicity
H_1 = - Σ p_i log (p_i)   = Boltzmann functional = plain old entropy
H_∞ = - log(max(p_i)))    = adamance             = "min-entropy"
```
where the sums run over all accessible elements of the ensemble.

### Suggestion 2:
Include not just the definition, but a discussion of the *significance*  of H_α in general and H_∞ in particular.  This includes some discussion of threat models.  Under some threat models, the plain old entropy H_1 is a useful measure, while under other threat models H_∞ is more appropriate.

One useful observation is that a small H_0 guarantees the problem is easy for the attacker, while a large H_∞ guarantees it is hard for the attacker.

### Suggestion 3:
Link to a tutorial where these issues are discussed in more detail.

**Comment by kerrymckay** [comment]
For terminology, please refer to the draft Special Publication 800-90B. This code package is provided to help people review the draft. It is not intended to be a standalone product (or even a final product), nor is it intended to provide a complete picture of entropy or the entropy assessment process.
