### ISSUE TITLE
Verbose flag in iid_main.cpp is not optional

### ISSUE THREAD

**Issue by zrlsid** [usnistgov/SP800-90B_EntropyAssessment#100]
The argument check in the iid_main.cpp does not allow to leave out the verbose flag. Please set the argument check to "argc<5" in order to allow verbose flag to be set optional. This would comply with the usage message of the program.

**Comment by joshuaehill** [comment]
The parameter checking is somewhat idiomatic; I'll try to replace it with a more traditional "getopt" based approach this weekend.

**Comment by joshuaehill** [comment]
This is now addressed in pull request #99.

**Comment by zrlsid** [comment]
@joshuaehill using getopt() like you did in the pull request #99 one has to adjust the "usage" for all main applications: ea_iid, ea_non_iid, ea_conditioning, and ea_restart. Due to the fact that you expect all the flags to be present in-front of the remaining command line parameters, e.g. file-name. Otherwise your code does not work: E.g.

$ ./ea_iid <-i|-c> <-a|-t> [-v] <file_name> <bits_per_word>

**Comment by joshuaehill** [comment]
That is surely the conventional ordering for options, but getopt() doesn't appear to actually require that ordering (I haven't widely tested this statement, but surely the getopt included with the particular flavor of ubuntu I'm using doesn't require this ordering). Does the historic ordering not work on your system with this getopt code?

**Comment by zrlsid** [comment]
I'm testing it right now on a MacOS and here it does not work, if I do not stick strictly to the "historic" ordering.

**Comment by joshuaehill** [comment]
Huh. OK, I'll update the pull request with the different ordering.

**Comment by joshuaehill** [comment]
The pull request was updated to document the ordering of command line parameters (which is apparently enforced on some implementations of getopt).
