### ISSUE TITLE
libdivsufsort

### ISSUE THREAD

**Issue by QuentinGouchet** [usnistgov/SP800-90B_EntropyAssessment#113]
In the README.md, please provide guidance about how to obtain the libdivsufsort library on Linux:

Set `LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib` to link to shared libraries located in `/usr/local/bin`. Note that this is only valid for this shell session.

Edit `/etc/ld.so.conf` to add on a newline: `/usr/local/lib` to make it permanent. It will then look something like:
```
include ld.so.conf.d/*.conf
/usr/local/lib
```

Then:
```
ldconfig
git clone https://github.com/y-256/libdivsufsort
mkdir libdivsufsort/build
cd libdivsufsort/build
cmake -DCMAKE_BUILD_TYPE="Release" -DCMAKE_INSTALL_PREFIX="/usr/local" ..
make && sudo make install
```

**Comment by joshuaehill** [comment]
This is rather distribution dependent. Your outlined procedure is reasonable for manually installing a new library. On, for example, On newer Ubuntu distributions, you can install it using "sudo apt-get install libdivsufsort-dev". There is a substantial amount of variation from distribution to distribution.

It's not clear to me that we want to develop and maintain per-distribution instructions of how to install the build prerequisites. Perhaps we could include this as user-maintained information in the wiki?

**Comment by QuentinGouchet** [comment]
Hi Joshua,

I did see that it was available for Ubuntu. But not for any Red Hat based
distros as far as I know.

Which wiki are you using? As long as the information is somewhere, I think
it's fine. Just wanted to provide other people with a quick way to get it
working!

**Comment by joshuaehill** [comment]
The github wiki for this project would work, though I'm not aware that it has any content just yet (aside from the main page that I just created as a test). It's also possible that NIST has some pre-existing resource that might work. Any suggestions, @celic ?

**Comment by celic** [comment]
A GitHub wiki would work well.

**Comment by joshuaehill** [comment]
@QuentinGouchet Could you make a page within the GitHub project wiki for distribution-specific build instructions, and add this information to that page?

**Comment by QuentinGouchet** [comment]
Absolutely!

**Comment by QuentinGouchet** [comment]
I created a wiki page for it. I will now close this issue.

**Comment by joshuaehill** [comment]
Thanks! That looks good!

**Comment by dj-on-github** [comment]
I had success compiling the y-256 libdivsufsort that is available on github.
