### ISSUE TITLE
The current tools do not support making an IID claim

### ISSUE THREAD

**Issue by joshuaehill** [usnistgov/SP800-90B_EntropyAssessment#121]
To support an IID claim, SP800-90B requires performing the tests in SP800-90B section 5 (implemented in ea_iid) on:
1. The sequential dataset described in item 1 of Section 3.1.1.
2. The row and **column datasets** described in item 3 of Section 3.1.1.
3. If a conditioning component that is not listed in Section 3.1.5.1.1 is used, the conditioned sequential dataset (described in item 2 of Section 3.1.1).

The ea_iid would support  tests number 1 and 3, but we have no way of extracting the column data from the testing conducted by ea_restart, so we can't presently perform the testing in 2.

**Comment by joshuaehill** [comment]
I added a command "ea_transpose", which allows the tester to produce the column data set (using the raw data, as that's what you're supposed to do most of the testing with).

**Comment by atfilipi** [comment]
Adrian
-- 
[ Adrian Filipi | adrian@ubergeeks.com | 434.760.0971 ]
Your computer has too much computer in it and not enough typewriter.
     -- Strong Bad
