### ISSUE TITLE
Uninitialized comparison in max_map in shared/utils.h

### ISSUE THREAD

**Issue by mclearn** [usnistgov/SP800-90B_EntropyAssessment#122]
In shared/utils.h, `max_key` is uninitialized as detected by static analysis tools.  However, since key values appear to be initialized to 1 (and only grow) in all use cases, functionally, it shouldn't be an issue since `itr->second > max_cnt` will always result as true before the equality check comes into play.  To avoid static analysis warnings, perhaps consider setting `max_key` to 0.

**Comment by joshuaehill** [comment]
Pull request #118 resolves this by just removing this function (an, indeed, removing the fundamentally linear search that is implemented in this function!)
