### ISSUE TITLE
invalid p(max) value

### ISSUE THREAD

**Issue by JohnDenker** [usnistgov/SP800-90B_EntropyAssessment#13]
### Recipe:

`time python noniid_main.py -v urandom-100.bin 8`
### Observed result:

`Markov Estimate (map 6 bits): p(max) = 1.27731e-206, min-entropy = 5.34347`

The p(max) value is impossible, and is inconsistent with the reported min-entropy.  This means the integrity of the calculations is seriously open to question.
### Additional observation:

Running the same command on a different data file produces a numerically-different but equally-impossible p(max) value.

See attached file, which contains details on both examples.
[pmax.txt](https://github.com/usnistgov/SP800-90B_EntropyAssessment/files/392588/pmax.txt)

**Comment by efnar** [comment]
It's not clear to me what the nature of your objection is to this p(max) value. The reported probability is an upper bound for the probability that the constructed Markov source produces the most probable 128-symbol string. The reported min-entropy is the corresponding min-entropy, divided by 128.

For more details, you may want to refer to the specification of this test in the current draft of NIST SP800-90B and the Hagerty-Draper paper "Entropy Bounds and Statistical Tests".
