### ISSUE TITLE
Restart Test Input data format

### ISSUE THREAD

**Issue by sachin-taneja** [usnistgov/SP800-90B_EntropyAssessment#130]
Hi everyone,

I am referring to restart test for 800-90B, Section 3.1.4.1 "Constructing Restart Data" suggest to store data in 2D matrix form.

My understanding is that .bin file has storage as 1D array from start to end (correct me if i am wrong). So same input samples data storage format (like IID and non IID i.e. ) will work for the restart testing as well and difference is data samples from different restart.

I am saving the data in text format (single column) and converting to .bin file as per format:
Restart 1: sample 1
.
.
Restart 1: sample 1000
.
.
Restart 1000: sample 1
.
.
Restart 1000: sample 1000

I am in process of figuring this in the code, Any help is much appreciated related to this confusion.

**Comment by joshuaehill** [comment]
The binary file input for restart testing should be of the form:
(restart 1, sample 1) (restart 1, sample 2), ... (restart 1, sample 1000) (restart 2, sample 1) ... (restart 1000 sample 1000)
This appears to be exactly the format that you are describing. The code for calculating the row/column max counts is opaque, but if you work out what the code is doing, I think that it's correct.

**Comment by joshuaehill** [comment]
One detail: These restart samples must be 1 symbol per byte. If your data is wider than this, you have to map it down so that it can be encoded into one symbol per byte (just like for doing the statistical testing...)

**Comment by sachin-taneja** [comment]
@joshuaehill Thanks a lot once again for sharing your views. I appreciate once again.

I am not sure (how much obvious the data arrangement is and major doubt comes from Section 3.1.4.1) but i think this should be added to wiki.

Share your thoughts.

**Comment by joshuaehill** [comment]
That surely falls into the category of "I thought we already had that written down somewhere", but I don't actually see it anywhere. This information should probably go into both the README file and the ea_restart help output.
