### ISSUE TITLE
1. Why binary data is converted into 1s and 2s in estimators section, where file is in text format? How wordsize bit conversion is done?

### ISSUE THREAD

**Issue by bitstream111** [usnistgov/SP800-90B_EntropyAssessment#147]

**Comment by joshuaehill** [comment]
In general, this tool is an implementation of the tests specified in NIST SP 800-90B. You should read that document for an explanation as to how the analysis is expected to work.

This tool does not support inputting text data (or rather, all data is treated as binary data). It is required to be composed of symbols that are presented 1 symbol per byte.

I'm not really sure what you are asking. Can you be more specific, provide data that causes the behavior that you are asking about, and explain what you would expect to see?

**Comment by bitstream111** [comment]
in no_iid file is accepted as test file for estimation but it perform conversion on binary as well(0 as 1 and 1 as 2)

**Comment by joshuaehill** [comment]
The ea_non_iid program does not translate values to 1 and 2; it does translate the data, but if there are "k" distinct symbols in the input, they are mapped to integers in the closed interval [0, k-1]. The non-iid estimators are all either categorical or invariant under any translation that preservers order, so this does not affect the results of the estimators.

**Comment by joshuaehill** [comment]
As a further comment, if you are literally feeding a stream of ascii '0' and '1' bytes, then that should work out, as ascii decimal digits are order preserving. (ascii '0' is 0x30 and ascii '1' is 0x31).

I further note that if you are feeding it a stream of ascii characters '0' and '1' and have newlines in there as well, then you've introduced a new symbol (linefeed '\n' symbol, ascii 0x0a) that you didn't really want in your data stream. As the linefeed is numerically smaller than ascii '0' and ascii '1', that would then become your 0 symbol, and you would be seeing the behavior that you are describing (where ascii '0' would be translated to 1, and ascii '1' would be translated to 2). If this is happening, your results are likely not meaningful.

**Comment by bitstream111** [comment]
Thank you Sir for you valuable feedback
