### ISSUE TITLE
Is there any library that can be used in LSR and T-Tuple estimate that can be placed libdivsufsort While coding in windows platform?

### ISSUE THREAD

**Issue by bitstream111** [usnistgov/SP800-90B_EntropyAssessment#148]

**Comment by joshuaehill** [comment]
Does libdivsufsort not work on windows? I'd think that it would compile just fine, perhaps with some small changes to reflect changes in compilation environments. Are you just running into problems with using CMake?

**Comment by celic** [comment]
I do know that libdivsufsort is available on Windows and the library can be compiled using `clang`. We were able to compile on Windows pulling in all the needed dependencies. Please look at the `Windows10` branch on this project as some code changes were made to get there.
