### ISSUE TITLE
what is the reason behind fixed values that are hard coded in  almost all estimators,like no of occurance is atleast 35 in t-tuple estimate as well as LSR estimate.

### ISSUE THREAD

**Issue by bitstream111** [usnistgov/SP800-90B_EntropyAssessment#149]

**Comment by joshuaehill** [comment]
This (again) is specified in SP 800-90B.

The choice of a particular constant is surely a tune-able parameter, but the underlying distribution does suggest that some constant in this rough range is appropriate. If you compare the last 90B draft with the final document, you'll notice a refinement that allows for some common processing between these two tests.
