### ISSUE TITLE
number of windows that are four and are defined as 63,255,1023,4095.what is the reason behind selecting these four windows in particular 

### ISSUE THREAD

**Issue by bitstream111** [usnistgov/SP800-90B_EntropyAssessment#150]

**Comment by joshuaehill** [comment]
The proximate reason why this tool does this is because SP 800-90B says to do so.

The reason that 90B does this is somewhat arbitrary. I would think that a better approach would be prime values up to some bound. The values here are 1 off from a few particular powers of 2.
