### ISSUE TITLE
i am giving binary data to non_iid estimators but it  shows  alph_size=4 for binary data(0,1)

### ISSUE THREAD

**Issue by bitstream111** [usnistgov/SP800-90B_EntropyAssessment#154]

**Comment by joshuaehill** [comment]
If you provide a sample file, I can tell you what is going on.

If I were to guess, I'd guess that your binary data is not being presented in a reasonable format. Each symbol in the data set should be encoded as a single byte, and there should be no bytes in the provided file that are not associated with symbols. My uninformed speculation is that you are actually feeding the tool data in ascii format with MSDOS newline conventions (where the end-of-line is 0x0d 0x0a). That would give you 4 symbols, and the results of the resulting analysis would be nonsense.

**Comment by joshuaehill** [comment]
@celic I think that you can close this issue.
