### ISSUE TITLE
Flags not supported on MacOS

### ISSUE THREAD

**Issue by QuentinGouchet** [usnistgov/SP800-90B_EntropyAssessment#158]
Two compilation flags are not supported on MacOS Mojave (10.14.6). I created a patch that compiles on MacOS:

diff --git a/cpp/Makefile b/cpp/Makefile
index d5ac13f..8b258c7 100644
--- a/cpp/Makefile
+++ b/cpp/Makefile
@@ -1,5 +1,11 @@
 CXX = g++
-CXXFLAGS = -std=c++11 -fopenmp -O2 -msse2 -ffloat-store -march=native
+CXXFLAGS = -std=c++11 -O2 -msse2 -march=native
+
+UNAME_S := $(shell uname -s)
+ifneq ($(UNAME_S),Darwin)
+       CXXFLAGS += -fopenmp -ffloat-store
+endif
+
 #CXX = clang++-8
 #CXXFLAGS = -Wno-padded -Wno-disabled-macro-expansion -Wno-gnu-statement-expression -Wno-bad-function-cast -fopenmp -O1 -fsanitize=address -fsanitize=undefined -fdenormal-fp-math=ieee -msse2 -march=native
 #static analysis in clang using

**Comment by joshuaehill** [comment]
If you don't have a compiler that supports OpenMP ("-fopenmp"), then your test tool is going to be profoundly slow as compared to platforms that do support OpenMP on any platform with multiple cores (specifically, on all modern hardware); all threading is done using OpenMP. If you're going to be doing much with this tool on this platform, you should install a compiler that supports OpenMP functionality.

For GCC, the "-ffloat-store" forces IEEE forces IEEE 754 behavior on Intel platforms; you may see a different accumulation of floating point error than occurs in the reference tool absent this option. That said, the default compiler on all recent MacOS platforms is actually clang behind the scenes. You should try using the clang options that are in the Makefile.

**Comment by joshuaehill** [comment]
@celic I think that this issue can be closed.
