### ISSUE TITLE
if I am  evaluating  noise source, is it necessary to implement health test while evaluating noise source or we just have to make sure that submitter has implemented health test on noise source?

### ISSUE THREAD

**Issue by bitstream111** [usnistgov/SP800-90B_EntropyAssessment#160]

**Comment by celic** [comment]
Hi, if you have questions about SP800-90B, it is best to email the CMVP.

**Comment by joshuaehill** [comment]
It may also be useful to discuss such questions with one of the CST Laboratories that help vendors through the testing process.
