### ISSUE TITLE
ea_restart generates a different result than ea_non_iid

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/SP800-90B_EntropyAssessment#161]
Background: we obtained 1000 files. Each file contains the data from one
reboot -> we have 1000 reboots. Each file contains exactly 1000 bytes -> each
entropy event value is 8 bits.

To calculate the restart entropy, we concatenated the data to form a file with
1,000,000 bytes (first 1000 bytes is 1st reboot, 2nd 1000 bytes is 2nd reboot,
...)

We calculate the restart min entropy with the following command:

SP800-90B_EntropyAssessment/cpp/ea_restart -v -n entropy_consolidated 8 1

I.e. we assume that 1 bit of entropy is present in each 8 bit event value.

We obtain the following result from ea_restart:

H_r: 0.020635
H_c: 6.638399
H_I: 1.000000

*** min(H_r, H_c) < H_I/2, Validation Testing Failed ***

H_r is the min entropy of all 1000 row-wise (i.e. each reboot) data sets -
specifically the following tests failed:

        LRS Test Estimate (Rows) = 0.031915 / 8 bit(s)
        LRS Test Estimate (Cols) = 7.718814 / 8 bit(s)

        Multi Markov Model with Counting (MultiMMC) Prediction Test Estimate
(Rows) = 0.020635 / 8 bit(s)
        Multi Markov Model with Counting (MultiMMC) Prediction Test Estimate
(Cols) = 6.638405 / 8 bit(s)

Now, I considered the row-wise entropy data calculation which ought to perform
the following steps:

- take each row (which is depicted by one of the 1000 files)

- calculate the SP800-90B min entropy value for each row

- take the minimum value of all of the 1000 min entropy values as the result

I did that manually:

- calculate for each of the converted files the min entropy value:

i=1; while [ $i -le 1000 ]; do SP800-90B_EntropyAssessment/cpp/ea_non_iid -i -
a -v entropy_$i.8 | grep min | cut -d ":" -f 2 >> out; i=$((i+1)); done

This call takes the last line of the output and just prints the number.

- find the minimum value out of the generated 1000 min entropy values

I get the following 1000 min entropy values - all of these values are above
3.5 bits of entropy per 8 bit value - i.e. the data we do expect and which
indicates that we have good entropy.

Comparing the minimum value from the following data of about 3.5 with the
ea_restart value of 0.02 seems to imply that there is some issue in the tool.
I was not able to identify the issue.

 4.701397
 4.431325
 4.607364
 4.088958
 4.088958
 4.555440
 4.052039
 4.392306
 4.568867
 4.316593
 4.902553
 4.280155
 3.870046
 4.215308
 5.787172
 4.670336
 5.229744
 4.444283
 3.962015
 3.837080
 3.628431
 4.371097
 5.107124
 4.745913
 4.234549
 4.406046
 4.193832
 5.549353
 5.524997
 4.004948
 4.249694
 4.511792
 4.541834
 4.719606
 4.160180
 4.741085
 4.345837
 4.575618
 4.537261
 4.374811
 4.388925
 4.046600
 4.498049
 5.277829
 4.763555
 4.494742
 4.106376
 3.774424
 3.980060
 4.582334
 4.287007
 3.925087
 4.414403
 3.888862
 4.992541
 3.654533
 4.082118
 4.005820
 4.161396
 5.117366
 4.376861
 5.680368
 4.403266
 5.036825
 4.310416
 5.101564
 5.157914
 4.604207
 5.075262
 4.732198
 4.782736
 4.676756
 4.420287
 4.034112
 3.890749
 4.198230
 4.076571
 5.317612
 3.909077
 5.290645
 5.546562
 4.693293
 4.061661
 3.804944
 4.328871
 4.496868
 4.196813
 4.446002
 4.489138
 4.421259
 3.892572
 3.719359
 3.677809
 4.298930
 4.180696
 4.147105
 5.410725
 4.324512
 4.259767
 4.940833
 4.178289
 4.844696
 3.995986
 4.334173
 4.119458
 4.559818
 4.834300
 4.477076
 4.605266
 4.109924
 4.878695
 4.368996
 3.643381
 3.972657
 4.391084
 4.185774
 4.252367
 4.442709
 5.351017
 4.324627
 3.872045
 4.301982
 4.736269
 5.383453
 4.001801
 3.827730
 5.279747
 4.351618
 4.817177
 4.759740
 4.496826
 4.774485
 4.536028
 4.799666
 4.144609
 5.073828
 3.933988
 3.954065
 5.265383
 4.826059
 4.266002
 4.266002
 5.471269
 5.680368
 5.680368
 3.955689
 4.119897
 4.529028
 4.611398
 3.685556
 3.827872
 4.460338
 5.298623
 4.266079
 4.145983
 4.763832
 4.856291
 3.873493
 4.011806
 4.371716
 4.074049
 3.869906
 3.778745
 3.938096
 4.418865
 4.492837
 4.443239
 4.391855
 4.294884
 4.252473
 3.831914
 5.081067
 4.124099
 3.914671
 3.939763
 4.678676
 5.666602
 4.356420
 4.133738
 3.753060
 4.063598
 4.550621
 5.649543
 4.647335
 4.265235
 4.936504
 4.400116
 3.916190
 3.921511
 4.458488
 4.813829
 3.694974
 5.512821
 5.321015
 3.996465
 4.220831
 4.452225
 4.362960
 4.112144
 4.459190
 4.847489
 5.074694
 4.234206
 4.184895
 4.506785
 4.277157
 3.498104
 4.019710
 4.010951
 3.407118
 4.683059
 4.504747
 4.026575
 4.334393
 4.922231
 4.840961
 4.250923
 4.029212
 4.887864
 4.643767
 4.640803
 4.312582
 4.313583
 4.266695
 4.447505
 4.286466
 4.182842
 4.099342
 4.503243
 3.698408
 4.467471
 4.382984
 4.542987
 4.125414
 4.615147
 5.486576
 5.787172
 4.955667
 5.518572
 3.662585
 4.470425
 4.563456
 4.723353
 4.389789
 4.581761
 4.606183
 4.096521
 4.433121
 4.174863
 4.557549
 3.717061
 4.274898
 5.321946
 4.609472
 4.474385
 5.510500
 4.270852
 3.795003
 4.476486
 3.609293
 5.312435
 5.083405
 4.247712
 3.583907
 4.352385
 4.002729
 4.109536
 4.252588
 4.755093
 3.738103
 3.829583
 5.680368
 4.796753
 4.150114
 4.494763
 4.463596
 4.236027
 4.987045
 5.589864
 4.418631
 5.582172
 4.025559
 4.706597
 3.882111
 4.243564
 4.098240
 4.659543
 4.986942
 4.594700
 4.630371
 4.738963
 4.516826
 4.581496
 4.274655
 3.711236
 4.100999
 4.142746
 4.549719
 4.862179
 5.480860
 4.307000
 4.985278
 4.923491
 3.893657
 4.107575
 4.566100
 3.920992
 4.067356
 4.359821
 5.008605
 4.533794
 5.787172
 5.024113
 3.750187
 4.537262
 4.815644
 4.159585
 4.999567
 5.249690
 3.922842
 4.400333
 4.232488
 3.958609
 4.525212
 4.276949
 5.017237
 3.678827
 4.269905
 4.483064
 4.090805
 4.664767
 3.917408
 4.140552
 4.049286
 5.207071
 4.286191
 4.156174
 4.225326
 5.183906
 4.272084
 3.963135
 4.132238
 4.855152
 5.787172
 4.212285
 4.814779
 4.090299
 4.219437
 4.446892
 5.680368
 4.914857
 4.652151
 4.659341
 3.595533
 5.083512
 5.018967
 4.796220
 5.155600
 4.446881
 4.175762
 4.443863
 4.004481
 4.336148
 3.925770
 4.741886
 5.015907
 5.240219
 3.659799
 3.886133
 3.823618
 4.564859
 3.826595
 4.755176
 4.470560
 5.051902
 5.787172
 3.975379
 4.590717
 4.082613
 4.181251
 4.490226
 4.472539
 4.198192
 5.231763
 4.887489
 5.028603
 4.069542
 4.718806
 4.050698
 4.481169
 5.183756
 5.123345
 4.226576
 5.174188
 3.760843
 4.374198
 4.352552
 4.090288
 4.127522
 4.034924
 4.548837
 3.917146
 4.253527
 5.214271
 4.021969
 4.377527
 4.221778
 4.268639
 3.925607
 4.949931
 4.783268
 4.646872
 4.293613
 5.333992
 4.792800
 4.748909
 4.015690
 4.600384
 4.157598
 3.898564
 4.346736
 4.115924
 4.433360
 4.795831
 4.127570
 5.016376
 4.350004
 4.772844
 4.917495
 4.565719
 3.952016
 5.787172
 4.453641
 4.019261
 3.561178
 4.049497
 4.232548
 3.985596
 4.694968
 4.398462
 3.981905
 3.822963
 4.883497
 4.590738
 3.912295
 4.116814
 4.826153
 4.482914
 4.300701
 5.150754
 4.212352
 4.144817
 4.644969
 5.135542
 3.816448
 4.516040
 4.723143
 4.305925
 4.203295
 4.246091
 4.217610
 4.394954
 4.583574
 4.294097
 5.453346
 4.483165
 4.394977
 4.030466
 5.465388
 5.260366
 4.083794
 5.582172
 5.680368
 3.537058
 4.140330
 4.614276
 4.545999
 3.822143
 3.542959
 4.196221
 4.549546
 3.984191
 4.393064
 5.486046
 4.314445
 3.739517
 4.327728
 4.951752
 4.928185
 4.175902
 4.810332
 4.333443
 4.317919
 5.105226
 4.172153
 4.406671
 4.114629
 4.031372
 3.966357
 4.353787
 4.673734
 3.687803
 5.326817
 5.493493
 4.050157
 3.985408
 3.918729
 4.271234
 3.677602
 4.333253
 4.293019
 4.619751
 4.813838
 4.946598
 3.642625
 4.533680
 4.088700
 4.421441
 5.394732
 4.975894
 3.932514
 5.345040
 5.179092
 4.232293
 4.337033
 5.251123
 5.469051
 4.723254
 4.853939
 4.016000
 4.082393
 4.378233
 3.671549
 3.930633
 4.475817
 4.638029
 4.312111
 3.846532
 4.211783
 4.868282
 4.406514
 5.012266
 5.061179
 5.582172
 4.726842
 4.726842
 4.362622
 3.893676
 3.893676
 4.466341
 4.663450
 3.635629
 3.884497
 4.408633
 4.361837
 4.741534
 3.995866
 4.633134
 3.869270
 5.198162
 4.482078
 4.191524
 4.388663
 4.452872
 3.985903
 4.189081
 4.463666
 4.182875
 4.993156
 5.680368
 4.512004
 4.343057
 3.977755
 4.245268
 4.882737
 5.451698
 4.848228
 4.656050
 4.168040
 4.056718
 3.805693
 4.910765
 4.344524
 4.406005
 4.971618
 4.134930
 4.946367
 4.337303
 4.019443
 5.084595
 4.302842
 4.594472
 3.809021
 4.265319
 3.942377
 4.269085
 3.447506
 3.995696
 4.711737
 4.471511
 4.910547
 4.612969
 4.816711
 3.499008
 4.331696
 4.393103
 4.242426
 4.882829
 3.547736
 4.565880
 4.526701
 5.224071
 4.174349
 4.613099
 4.405077
 4.366003
 5.079175
 4.477847
 4.977874
 4.366827
 4.262317
 5.383649
 4.131858
 5.548676
 4.630151
 3.689394
 4.971244
 4.926393
 4.042981
 3.984731
 5.480860
 4.958945
 4.444810
 4.016101
 4.661663
 4.102250
 4.789999
 4.591874
 4.682066
 4.646814
 4.466526
 4.553429
 4.586275
 4.053045
 3.882195
 4.580850
 5.324105
 4.381508
 4.371228
 3.908676
 4.163119
 4.332842
 4.405603
 4.007187
 4.582305
 4.177053
 3.888979
 5.582172
 4.864812
 4.497069
 3.499506
 4.166311
 3.835573
 4.306258
 4.256957
 4.120730
 5.469051
 3.704257
 5.787172
 4.780939
 5.603848
 5.377078
 3.781640
 4.924292
 4.195426
 4.811325
 4.329978
 3.951440
 5.285784
 3.745195
 3.880469
 4.733937
 4.039810
 4.208452
 4.294855
 4.252102
 4.844280
 4.698843
 4.091856
 4.111278
 3.943919
 4.220750
 4.414915
 4.598703
 4.109680
 4.326285
 4.177139
 4.236100
 4.489956
 4.674927
 3.986743
 4.616355
 4.257596
 5.233576
 5.259502
 4.412395
 4.776297
 4.571985
 4.210547
 4.534011
 4.055407
 4.324842
 4.102001
 4.096405
 4.112510
 4.203059
 4.039122
 4.973659
 4.362875
 4.919537
 5.196849
 4.367566
 4.720809
 4.369125
 4.616088
 5.402335
 3.830090
 4.175081
 4.084307
 4.136781
 4.432233
 3.831575
 3.971292
 4.021390
 4.886233
 4.572720
 4.099266
 4.385157
 4.772041
 4.025863
 4.100197
 4.323703
 4.314322
 4.770046
 5.602514
 4.484283
 4.143611
 5.155812
 4.409832
 4.255752
 4.692205
 4.083443
 4.257612
 4.586382
 4.251897
 5.194316
 4.100262
 4.016054
 4.395042
 4.185804
 4.165215
 4.290890
 4.329738
 4.683845
 4.044065
 4.235734
 5.335545
 4.772017
 4.356434
 4.712795
 4.138899
 4.257636
 4.446027
 4.088493
 3.864191
 4.419215
 3.864019
 3.921680
 5.577328
 4.403727
 4.580583
 4.265685
 5.170544
 4.641018
 4.510923
 4.321928
 4.412498
 4.097639
 4.033384
 4.316335
 4.225241
 4.090708
 4.892945
 4.394972
 4.754288
 4.223358
 4.048513
 5.165329
 3.896944
 4.042560
 4.663585
 5.131221
 3.728426
 4.387445
 5.159458
 5.432556
 3.934588
 5.454740
 5.009665
 4.081797
 5.676599
 4.732104
 4.299555
 5.621399
 5.135746
 4.316800
 3.854151
 4.844850
 3.701992
 4.481983
 4.311231
 5.524676
 3.781386
 4.811669
 4.811964
 4.790500
 3.945757
 4.554874
 4.635319
 5.366895
 4.287151
 3.984481
 4.933541
 4.326981
 5.015733
 4.662067
 4.461802
 4.232145
 3.975192
 5.072130
 4.751916
 3.847013
 4.266976
 4.816321
 4.420233
 4.186927
 4.408350
 4.138492
 4.825285
 4.527237
 4.778118
 5.167253
 3.830586
 4.245099
 4.198020
 4.183396
 3.944711
 4.138918
 4.288927
 4.803374
 4.206937
 4.264217
 3.956521
 5.123345
 4.719752
 4.683279
 4.551662
 4.473329
 4.523690
 4.174311
 4.208170
 4.099537
 4.213172
 3.802106
 4.808821
 4.820604
 4.321891
 4.343521
 4.879213
 4.290806
 5.089319
 4.202775
 3.937653
 4.408370
 5.680368
 4.364442
 4.603112
 4.305936
 5.582172
 4.773192
 3.747389
 4.486009
 4.297534
 4.241476
 4.205546
 4.183311
 4.201285
 4.052510
 5.097647
 4.829012
 4.554287
 4.313825
 4.115066
 4.770848
 4.937417
 3.989475
 4.542978
 3.794024
 4.693540
 4.067700
 4.135937
 4.050125
 5.699576
 4.531740
 4.388119
 3.844436
 5.034551
 3.701100
 3.565383
 4.975169
 4.400040
 5.229368
 5.398856
 4.211319
 4.175519
 4.535532
 4.466271
 5.355779
 4.258779
 4.262466
 3.799696
 5.680368
 4.516845
 4.975117
 5.179639
 4.025438
 4.114928
 4.815677
 4.081768
 5.090056
 4.585293
 4.420877
 4.356566
 3.758273
 4.155765
 4.196912
 4.540426
 5.208557
 4.437828
 4.384298
 5.093216
 4.924439
 4.516022
 4.134900
 3.989345
 4.067544
 3.899501
 5.787172
 4.069417
 3.849249
 4.664403
 5.098108
 4.549206
 4.208235
 4.697523
 3.900862
 4.104152
 3.820259
 4.366426
 4.573609
 3.774651
 3.830748
 5.122342
 3.932125
 3.475847
 4.273077
 4.262972
 4.568949
 4.670303
 4.307088
 3.826865
 3.909521
 4.214864
 4.879106
 4.708759
 4.429364
 4.457381
 4.198624
 5.416310
 4.641528
 5.680368
 4.036860
 4.407032
 4.050136
 4.554770
 5.001162
 4.479835
 4.168507
 5.173206
 4.260890

**Comment by joshuaehill** [comment]
So, I'm not quite sure exactly what's going wrong, but a few points:
* Could you please provide the underlying data sample so that I can replicate the issue? As we will see later,  the set of 1000 individual row files isn't useful, but I would like to examine at the file that results after you have concatenated all 1000 rows into a 1 million byte file.
* Next, taking the minimum of 1000 different values isn't what 90B asks you to do, and isn't what the tool does. Look at SP 800-90B Section 3.1.4.1 to identify the relevant data sets; the one you want for the 'H_r' is the "row dataset" described in that section; this is just the single 1 million byte restart file, where the first 1000 bytes from each restart are concatenated together.
* Performing tests on datasets of 1000 bytes isn't meaningful. The smallest sample supported by this test set is 1 million samples, so you're presumably seeing all sorts of warnings telling you that this testing isn't meaningful. If this is not the case, then something odd is going on that should be looked into.
* Last, the style of problem that you are seeing suggests that there is a very long repeated string, and the absence of such a string within each row suggests that that repeated string is actually a substantial repeated set of samples between two reboots. If that is the case, then this is exactly the sort of problem that the restart testing is supposed to detect.
