### ISSUE TITLE
Stuck in LRS Estimate

### ISSUE THREAD

**Issue by telmonteiro** [usnistgov/SP800-90B_EntropyAssessment#163]
Hi! I'm trying to test a 20 million byte-sized sample, but it gets stuck right after the t-tuple estimate. I tried reducing the sample size to 10 million, 5 million even to 1 million bytes, but it would always get stuck for hours/days. 
Though it works with 500 thousand bytes, I intended to get an estimate for the full 20MB.

Here's the output using one verbose and two verboses for the 10 million bytes sample (the output is similar to the other sizes I mentioned):

./ea_non_iid -i -a -v -l 0,10000000 ../bin/RawRandom_5.dat 8
Opening file: '../bin/RawRandom_5.dat'
Loaded 10000000 samples of 256 distinct 8-bit-wide symbols
Number of Binary Symbols: 80000000

Running non-IID tests...

Running Most Common Value Estimate...
Bitstring MCV Estimate: mode = 40001947, p-hat = 0.50002433749999997, p_u = 0.50016833073625866
        Most Common Value Estimate (bit string) = 0.999514 / 1 bit(s)
Literal MCV Estimate: mode = 111928, p-hat = 0.011192799999999999, p_u = 0.011278492395416184
        Most Common Value Estimate = 6.470282 / 8 bit(s)

Running Entropic Statistic Estimates (bit strings only)...
Bitstring Collision Estimate: X-bar = 2.4956254804858933, sigma-hat = 0.49998087101133543, p = 0.54796866074796802
        Collision Test Estimate (bit string) = 0.867835 / 1 bit(s)
Bitstring Markov Estimate: P_0 = 0.49997566249999997, P_1 = 0.50002433749999997, P_0,0 = 0.50412775102147478, P_0,1 = 0.49587224897852522, P_1,0 = 0.49582399076724942, P_1,1 = 0.50417600923275052, p_max = 8.4513781664308203e-39
        Markov Test Estimate (bit string) = 0.988094 / 1 bit(s)
Bitstring Compression Estimate: X-bar = 5.1327901495360555, sigma-hat = 1.0945666045533693, p = 0.077420044709657132
        Compression Test Estimate (bit string) = 0.615192 / 1 bit(s)

Running Tuple Estimates...
Bitstring t-Tuple Estimate: t = 614, p-hat_max = 0.97693703399913179, p_u = 0.97698026178134945

and for two verboses:

./ea_non_iid -i -a -v -v -l 0,10000000 ../bin/RawRandom_5.dat 8
Opening file: '../bin/RawRandom_5.dat'
Loaded 10000000 samples of 256 distinct 8-bit-wide symbols
Number of Binary Symbols: 80000000
Bitstring Most Common Value Estimate: Mode count = 40001947
Bitstring Most Common Value Estimate: p-hat = 0.50002433749999997
Bitstring Most Common Value Estimate: p_u = 0.50016833073625866
Bitstring Most Common Value Estimate: min entropy = 0.99951438190300679
Literal Most Common Value Estimate: Mode count = 111928
Literal Most Common Value Estimate: p-hat = 0.011192799999999999
Literal Most Common Value Estimate: p_u = 0.011278492395416184
Literal Most Common Value Estimate: min entropy = 6.4702819552843014
Bitstring Collision Estimate: v = 32056092
Bitstring Collision Estimate: Sum t_i = 80000000
Bitstring Collision Estimate: X-bar = 2.4956254804858933
Bitstring Collision Estimate: sigma-hat = 0.49998087101133543
Bitstring Collision Estimate: X-bar' = 2.4953980151720927
Bitstring Collision Estimate: Found p.
Bitstring Collision Estimate: p = 0.54796866074796802
Bitstring Collision Estimate: min entropy = 0.86783470950515607
Bitstring Markov Estimate: P_0 = 0.49997566249999997
Bitstring Markov Estimate: P_1 = 0.50002433749999997
Bitstring Markov Estimate: P_{0,0} = 0.50412775102147478
Bitstring Markov Estimate: P_{0,1} = 0.49587224897852522
Bitstring Markov Estimate: P_{1,0} = 0.49582399076724942
Bitstring Markov Estimate: P_{1,1} = 0.50417600923275052
Bitstring Markov Estimate: p-hat_max = 8.4513781664308203e-39
Bitstring Markov Estimate: min entropy = 0.9880938209352732
Bitstring Compression Estimate: X-bar = 5.1327901495360555
Bitstring Compression Estimate: sigma-hat = 1.0945666045533693
Bitstring Compression Estimate: X-bar' = 5.1320179914976336
Bitstring Compression Estimate: Found p.
Bitstring Compression Estimate: p = 0.077420044709657132
Bitstring Compression Estimate: min entropy = 0.61519150816594603
Bitstring t-Tuple Estimate: t = 614
Bitstring t-Tuple Estimate: p-hat_max = 0.97693703399913179
Bitstring t-Tuple Estimate: p_u = 0.97698026178134945
Bitstring t-Tuple Estimate: min entropy = 0.033598679590137848

I'm using 64-bit python version. Any help would be highly appreciated.

**Comment by joshuaehill** [comment]
If you can make an example data sample available, I could try to determine what is going on.

A few observations:

- The t-tuple behavior that you are seeing (t = 614) suggests that substrings of 614 symbols repeat at least 35 times, which suggests that this source outputs long sets of repeated strings. This may be made worse by a data formatting problem, but the assessed entropy is probably going to be quite low.
- You may be seeing a problem in the LRS test because the longest repeated substring is evidently quite large, and it turns out that the computational task associated with the LRS test scales with the length of this string.
- You examples all seem to use the C++ tool, not the Python tool. If you are actually using the Python tool, you shouldn't. It is hundreds of times slower than the C++ version, it was an implementation of an outdated version of the (then) draft SP 800-90B standard, and it has a bunch of bugs that aren't fixed.

**Comment by telmonteiro** [comment]
Thank you for the reply.

I'm in fact using the C++ tool, I just use Python in order to run the tests, so it was my mistake.

[
[RawRandom_1220MB.zip](https://github.com/usnistgov/SP800-90B_EntropyAssessment/files/6539747/RawRandom_1220MB.zip)

](url)

> 
> 
> If you can make an example data sample available, I could try to determine what is going on.
> 
> A few observations:
> 
>     * The t-tuple behavior that you are seeing (t = 614) suggests that substrings of 614 symbols repeat at least 35 times, which suggests that this source outputs long sets of repeated strings. This may be made worse by a data formatting problem, but the assessed entropy is probably going to be quite low.
> 
>     * You may be seeing a problem in the LRS test because the longest repeated substring is evidently quite large, and it turns out that the computational task associated with the LRS test scales with the length of this string.
> 
>     * You examples all seem to use the C++ tool, not the Python tool. If you are actually using the Python tool, you shouldn't. It is hundreds of times slower than the C++ version, it was an implementation of an outdated version of the (then) draft SP 800-90B standard, and it has a bunch of bugs that aren't fixed.

**Comment by joshuaehill** [comment]
The longest repeated substring in that dataset is 656384 symbols long, and the t value for the (literal) data is 166. As such, the tool needs to estimate the W-tuple collision entropy for every tuple length between these two values. That will take a while to perform the calculation, but it should eventually work out.

This is an incredibly long repeated substring for a data set of this size, and this suggests that the assessed entropy is going to be very very low.

**Comment by joshuaehill** [comment]
I'll summarize: the tool seems to be working fine, but this specific estimator detects defects in the provided data that are so large that it takes the tool quite a while to properly calculate just how low the estimate ought to be.
