### ISSUE TITLE
g++: error: unrecognized command line option ‘-msse2’

### ISSUE THREAD

**Issue by yuyinw** [usnistgov/SP800-90B_EntropyAssessment#164]
hello celic， when i  excute make at  raspi environment , it prompt a error g++: error: unrecognized command line option ‘-msse2’

**Comment by joshuaehill** [comment]
You can remove this option; it is an attempt to trigger use of some extra intel instructions (which ARM doesn't have). I'm not sure if there's some corresponding ARM-relevant flag that would suggest that the optimizer do corresponding functionality using analogous instructions (e.g., the NEON instructions).

**Comment by joshuaehill** [comment]
As an aside, I've done some testing on a few ARM architectures, and it was considerably slower than on modern Intel systems. 

Additionally, no pi has comfortable amount of memory as compared to their core count, so you're not going to be able to do much parallel testing on such hardware.

**Comment by yuyinw** [comment]
1. thank you , i will try again.   
2. i have a question for you :  i see you also use the python tool (SP800_90b_tests-master) test ,  What's the difference between these two tools (that tool seem have no restart test,  is restart test important?)

thank you very mach

**Comment by joshuaehill** [comment]
Are you talking about DJ's tool? You should verify with DJ, but my impression is that almost everyone (including DJ) currently uses the NIST tool, and so DJ's tool is largely abandoned. 

The NIST tool was a bit rough on release, but is now in fairly good shape.

**Comment by yuyinw** [comment]
ok， thank you very math.

**Comment by yuyinw** [comment]
can i ask you  a question need your help , when i test cpu jitter ,
1.current_delta_value 2. out of entropy of cpu_jitter
which data should i use

thank you

**Comment by joshuaehill** [comment]
This is with the [Jitter Entropy Library](https://github.com/smuellerDD/jitterentropy-library)? 

This isn't the right venue for such questions; you should probably ask them in the appropriate project.

That said, I can answer your question: in most versions (all versions prior to JEnt v3.0.2) those two columns mean different things. I think that in these versions, you need to use the data in the second column to help establish a H_submitter value, but the actual raw data is present in the first column. As such, in these versions, you need to perform testing with both columns. In JEnt v3.0.2 (and presumably later?) in the default configuration, the two columns mean approximately the same thing, and are roughly comparable to the second column in the earlier versions.

**Comment by yuyinw** [comment]
thank you  very much,   joshuaehill!

**Comment by yuyinw** [comment]
hi
     i have a problem,   My environment is gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)  , i see it should  support c++11, but it always prompt error :

g++ -L /home/wyy/usr/local/lib/ -I  /home/wyy/usr/local/include/ iid_main.cpp -o ea_iid -lbz2 -lpthread -ldivsufsort
In file included from /usr/include/c++/4.8.2/array:35:0,
                 from shared/utils.h:15,
                 from iid_main.cpp:1:
/usr/include/c++/4.8.2/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
In file included from iid_main.cpp:1:0:
shared/utils.h:64:84: error: ‘uint32_t’ has not been declared
 bool relEpsilonEqual(double A, double B, double maxAbsFactor, double maxRelFactor, uint32_t maxULP)
                                                                                    ^
shared/utils.h: In function ‘bool relEpsilonEqual(double, double, double, double, int)’:
shared/utils.h:68:4: error: ‘uint64_t’ was not declared in this scope
    uint64_t Aint;
    ^
shared/utils.h:68:13: error: expected ‘;’ before ‘Aint’
    uint64_t Aint;
             ^
shared/utils.h:69:13: error: expected ‘;’ before ‘Bint’
    uint64_t Bint;
             ^

**Comment by joshuaehill** [comment]
Based on your warnings that's your compiler objecting to one of your system include files. This error doesn't seem to be related to this tool. I suggest that you upgrade your compiler to a modern version of GCC or Clang.

**Comment by yuyinw** [comment]
Thank  you , joshuaehill！
      It's hard to build an environment。
      1. In  my raspi,    it  prompt 
      /nist/SP800-90B_EntropyAssessment-master/cpp$ make
g++ -L /usr/local/lib/ -I /usr/local/include/ iid_main.cpp -o ea_iid -lbz2 -lpthread -ldivsufsort
/usr/bin/ld: /tmp/cczBETjr.o: in function `permutation_tests(data_t const*, double, double, int)':
iid_main.cpp:(.text+0x73b0): undefined reference to `omp_get_thread_num'
/usr/bin/ld: iid_main.cpp:(.text+0x77cc): undefined reference to `omp_get_thread_num'
/usr/bin/ld: iid_main.cpp:(.text+0x77d4): undefined reference to `omp_get_num_threads'
     2. in my redhat computer  ,  its so hard to install gcc 11.1 ,always report errors
     3. now i try  build environment at a ubuntu system , i hope it would be successful.

**Comment by yuyinw** [comment]
Finally done ， it is so easy  at  ubuntu environment.

**Comment by joshuaehill** [comment]
For your issue above, you need to include the OpenMP library, which for most gcc versions is selected by including the `-fopenmp` flag. (The included Makefile already does this, but you appear to be manually compiling).

**Comment by yuyinw** [comment]
thank you  joshuaehill!

**Comment by joshuaehill** [comment]
No problem. If your issue is resolved, please close this issue. Thanks!
