### ISSUE TITLE
when i test cpu jitter, what data should i use

### ISSUE THREAD

**Issue by yuyinw** [usnistgov/SP800-90B_EntropyAssessment#165]
hello 
       i have a question need your help , when i test cpu jitter ,
       1.current_delta_value    2. out of entropy of  cpu_jitter 
       which data should i use

thank you

**Comment by joshuaehill** [comment]
This isn't the appropriate venue for asking about procedures required to validation specific entropy sources. Please ask on the relevant [github project](https://github.com/smuellerDD/jitterentropy-library).

**Comment by yuyinw** [comment]
ok, thank you very much
