### ISSUE TITLE
window10 branch: Makefile:38: recipe for target 'restart_main.o' failed

### ISSUE THREAD

**Issue by yuyinw** [usnistgov/SP800-90B_EntropyAssessment#169]
HI
      I download SP800-90B_EntropyAssessment-Windows10, when i compile, it generate err:
       
F:\code\90b\SP800-90B_EntropyAssessment-Windows10\cpp>make
clang++ -Wno-padded -Wno-disabled-macro-expansion -Wno-gnu-statement-expression -Wno-bad-function-cast -fopenmp -O1 -fsanitize=address -fsanitize=undefined -fdenormal-fp-math=ieee -msse2 -march=native -fforce-enable-int128 -L C:\Users\skb1\csdprojects\libdivsufsort-master\out\build\x86-Debug\lib -L C:\Users\skb1\Downloads\getopt_mb_uni_vc10\getopt_mb_uni_vc10\bin\debug\dll -L C:\Users\skb1\csdprojects\bzip2-1.0.6-master_secondcopy -pthread -Xlinker /NODEFAULTLIB:msvcrt -I C:\Users\skb1\Downloads\getopt_mb_uni_vc10\getopt_mb_uni_vc10\getopt_mb_uni_vc10_dll -I C:\Users\skb1\csdprojects\unistd_h-master\include -I C:\Users\skb1\csdprojects\libdivsufsort-master\out\build\x86-Debug\include -I C:\Users\skb1\csdprojects\bzip2-1.0.6-master_secondcopy iid_main.cpp -o ea_iid.exe -lgetopt -llibbz2 -ldivsufsort
process_begin: CreateProcess(NULL, clang++ -Wno-padded -Wno-disabled-macro-expansion -Wno-gnu-statement-expression -Wno-bad-function-cast -fopenmp -O1 -fsanitize=address -fsanitize=undefined -fdenormal-fp-math=ieee -msse2 -march=native -fforce-enable-int128 -L C:\Users\skb1\csdprojects\libdivsufsort-master\out\build\x86-Debug\lib -L C:\Users\skb1\Downloads\getopt_mb_uni_vc10\getopt_mb_uni_vc10\bin\debug\dll -L C:\Users\skb1\csdprojects\bzip2-1.0.6-master_secondcopy -pthread -Xlinker /NODEFAULTLIB:msvcrt -I C:\Users\skb1\Downloads\getopt_mb_uni_vc10\getopt_mb_uni_vc10\getopt_mb_uni_vc10_dll -I C:\Users\skb1\csdprojects\unistd_h-master\include -I C:\Users\skb1\csdprojects\libdivsufsort-master\out\build\x86-Debug\include -I C:\Users\skb1\csdprojects\bzip2-1.0.6-master_secondcopy iid_main.cpp -o ea_iid.exe -lgetopt -llibbz2 -ldivsufsort, ...) failed.
make (e=2):
Makefile:30: recipe for target 'iid_main.o' failed
make: *** [iid_main.o] Error 2

**Comment by skbhaskarla** [comment]
That is correct, `clang++` compiler was used in the Windows 10 Makefile. It does need a cleanup since it has local file system path references to some 3rd-party libraries which are not native to Windows environment. 

Sources for Libdivsufsort, Bzip2, Getopt all had to be compiled separately for the dependencies to resolve.
