### ISSUE TITLE
Calculation of P_W in LRS Estimate in certain environments

### ISSUE THREAD

**Issue by g-g-sakura** [usnistgov/SP800-90B_EntropyAssessment#170]
If the data type long int is 32-bit, the denominator for calculating $P_W$ in LRS estimate overflows, i.e. the binomial coefficient $\binom{L - W + 1}{2}$ is beyond the upper limit of 32-bit taking into account that $L$ is order of 10^6 and actual values of $W$.

As a result, H_original becomes infinity and H_bitstring becimes 0.13 for truerand_8bit.bin.

**Comment by joshuaehill** [comment]
I should mention that the error-free rollover is clearly a bug, but the resolution to this bug would be to trigger an assert on such environments, so it wouldn't resolve in a particularly useful way for such architectures.

**Comment by g-g-sakura** [comment]
Thank you for its investigation. The temporary solution will be to use the proposed code in Windows 10 branch.
Taking into account that the denominator can not be expressed by 32-bit, the numerator (vector S in code) should also be expressed by 64-bit for consistency.
