### ISSUE TITLE
User's Guide missing

### ISSUE THREAD

**Issue by bertol-g** [usnistgov/SP800-90B_EntropyAssessment#176]
Hi, I've been brought to this project following the CRSC page 
https://csrc.nist.gov/publications/detail/white-paper/2016/05/12/user's-guide-running-draft-sp-800-90b-entropy-estimation-suite/final
I'd like to see the user's guide, but unfortunately the link provided is not working:
https://github.com/usnistgov/SP800-90B_EntropyAssessment/blob/master/user_guide.pdf
Could you please help me?
Thank you very much.
Kind regards

Gian Mario

**Comment by joshuaehill** [comment]
That appears to be a problem with the CSRC page. You can find the file you are looking for [here](https://tsapps.nist.gov/publication/get_pdf.cfm?pub_id=920697).

That said, this guide applies to the older Python version of this tool (which was an implementation of the 2016 draft of the 90B document), and this document has almost no connection to the tool presently here (which is an implementation of the 2018 final 90B document). I'm not aware that there is a corresponding document for the final tool.

**Comment by celic** [comment]
Ideally the documentation on GH here and the README address everything the user guide covered. 

Any documentation pointing to the python tool will be out of date. The python version of this code as @joshuaehill mentioned was not updated for the final version of SP 800-90B and I would strongly discourage using it.
