### ISSUE TITLE
TestCase (et al) values are incomplete and the meaning of the saved values is inconsistent

### ISSUE THREAD

**Issue by joshuaehill** [usnistgov/SP800-90B_EntropyAssessment#179]
It seems like there should be more coverage and consistency in the data being fed into NonIidTestCase classes.

There are instances where apparently irrelevant variable values (sometimes for variables that have not yet been calculated) are set (e.g., `lrs_res` is set across most of the tests, but it only is relevant to one of the test cases).

Some values that are useful for results summary are not saved (e.g., `ret_min_entropy` is saved, but the meaning of that value depends on the tests that were run (e.g., literal or bitstring versions of these tests?) In cases where both are run, only the last one run is saved in this structure. Likely both of these values should be consistently saved.

It isn't really clear why the non-final versions of `H_bitstring` and `H_original` are consistently saved, when the current test may or may not ultimately influence those values.

**Comment by joshuaehill** [comment]
I stuck some comments on the most recent commit. The one comment that I still have is that in most cases where the same estimator is run on both the literal data and the bitstring data (i.e., all such cases other than the t-tuple and LRS estimators), only the result for the literal testing is saved in the JSON data.

**Comment by celic** [comment]
Thanks for the heads up.
