### ISSUE TITLE
Crash with memory error in file SP90Bv2_predictors.py

### ISSUE THREAD

**Issue by msp79** [usnistgov/SP800-90B_EntropyAssessment#2]
Hi,

I am trying to run the non iid tests for draft2 for a file of size 1000000 bytes with 8 bit samle size.I am getting the below error. Below is the output. Please let me know if this a script issue or related to input.

D:\Documents\SP800-90B_EntropyAssessment-draft2>C:\Python27\python.exe noniid_main.py -v randbytes.bin 8
reading 1000000 bytes of data
Read in file randbytes.bin, 1000000 bytes long.
Dataset: 1000000 8-bit symbols, 256 symbols in alphabet.
Output symbol values: min = 0, max = 255

Running entropic statistic estimates:
- Most Common Value Estimate: p(max) = 0.0043054, min-entropy = 7.85964
- Collision Estimate: p(max) = 0.0101379, min-entropy = 6.6241
- Markov Estimate (map 6 bits): p(max) = 5.20577e-223, min-entropy = 5.76883
- Compression Estimate: p(max) = 0.00577569, min-entropy = 7.43579
- t-Tuple Estimate: p(max) = 0.00414, min-entropy = 7.91615
- LRS Estimate: p(max) = 0.00525307, min-entropy = 7.57262

Running predictor estimates:
Computing MultiMCW Prediction Estimate: 100 percent complete
        Pglobal: 0.004133
        Plocal: 0.002136
MultiMCW Prediction Estimate: p(max) = 0.00413327, min-entropy = 7.9185

Computing Lag Prediction Estimate: 100 percent complete
        Pglobal: 0.004127
        Plocal: 0.002136
Lag Prediction Estimate: p(max) = 0.00412689, min-entropy = 7.92073

Computing MultiMMC Prediction Estimate: 56 percent completeTraceback (most recent call last):
  File "noniid_main.py", line 135, in <module>
    pmax, minH = MultiMMC(dataset, verbose)
  File "D:\Documents\SP800-90B_EntropyAssessment-draft2\SP90Bv2_predictors.py", line 292, in MultiMMC
    M[d-1][tuple(S[i-d-2:i-2])] = Counter()
MemoryError

Thanks
Mahendra

**Comment by msp79** [comment]
The same error is seen when I run the non iid tests on data file truerand_8bit.bin file. Below is the error log.

D:\Documents\IPSec\SP800-90B_EntropyAssessment-draft2\>C:\Python27\python.exe noniid_main.py -v truerand_8bit.bin 8
reading 1000000 bytes of data
Read in file truerand_8bit.bin, 1000000 bytes long.
Dataset: 1000000 8-bit symbols, 256 symbols in alphabet.
Output symbol values: min = 0, max = 255

Running entropic statistic estimates:
- Most Common Value Estimate: p(max) = 0.00428909, min-entropy = 7.86511
- Collision Estimate: p(max) = 0.0127255, min-entropy = 6.29613
- Markov Estimate (map 6 bits): p(max) = 1.13787e-223, min-entropy = 5.78597
- Compression Estimate: p(max) = 0.00872433, min-entropy = 6.84074
- t-Tuple Estimate: p(max) = 0.004124, min-entropy = 7.92174
- LRS Estimate: p(max) = 0.00391357, min-entropy = 7.9973

Running predictor estimates:
Computing MultiMCW Prediction Estimate: 100 percent complete
        Pglobal: 0.003937
        Plocal: 0.002136
MultiMCW Prediction Estimate: p(max) = 0.0039373, min-entropy = 7.98858

Computing Lag Prediction Estimate: 100 percent complete
        Pglobal: 0.004073
        Plocal: 0.002136
Lag Prediction Estimate: p(max) = 0.00407281, min-entropy = 7.93976

Computing MultiMMC Prediction Estimate: 56 percent completeTraceback (most recent call last):
  File "noniid_main.py", line 135, in <module>
    pmax, minH = MultiMMC(dataset, verbose)
  File "D:\Documents\IPSec\NIAP\NIST_RNG\SP800-90B_EntropyAssessment-draft2\SP800-90B_EntropyAssessment-draft2\SP90Bv2_predictors.py", line 292, in MultiMMC
    M[d-1][tuple(S[i-d-2:i-2])] = Counter()
MemoryError

Thanks
Mahendra

**Comment by kerrymckay** [comment]
How much memory does your system have?

**Comment by msp79** [comment]
Hi,

System memory (RAM) is 32 GB. Free space on hard disk is 300 GB.

Is there a specific RAM requirement ? Please guide me if I need to try on a system with specific RAM size. 

Thanks
Mahendra

**Comment by msp79** [comment]
To add one more info, it is a windows-7, 64 bit system.

Thanks
Mahendra

**Comment by msp79** [comment]
Hi,

On a linux system with 16 GB RAM too I am unable to run the non iid tests. In this, the execution of MultiMMC Prediction estimate stops with memory error at the same line as mentioned above at 91%.

As per the above logs, this issue is consistently reproducible on both linux and windows. Please suggest how to proceed as I need to come up with min-entropy estimate for use with repetition and continuous health tests . 

Thanks
Mahendra

**Comment by kerrymckay** [comment]
Are you using 32-bit python or 64-bit python? If you are using 32-bit, the issue may be that you are hitting the memory limit for the process. Please try running it on a 64-bit python installation and let me know if that helps or if the issue persists.

**Comment by msp79** [comment]
Hey, Thanks a lot... After using Python 64 bit version, the memory issue is resolved.

Thanks
Mahendra

**Comment by kerrymckay** [comment]
Great! Thank you for letting us know about this -- we'll add a requirement to the user guide.

**Comment by msp79** [comment]
Hi, I ran the restart tests now with H_I = 5.76883... I got a bunch of logs below not given in the user guide pdf... I didn't see any issue though... It says Passed the restart tests... Could you please confirm if this is fine?

D:\Documents\SP800-90B_EntropyAssessment-draft2>d:\python64\python.exe -v restart.py jdirandbytes.bin 8 5.76883
# installing zipimport hook
import zipimport # builtin
# installed zipimport hook
# d:\python64\lib\site.pyc matches d:\python64\lib\site.py
import site # precompiled from d:\python64\lib\site.pyc
# d:\python64\lib\os.pyc matches d:\python64\lib\os.py
import os # precompiled from d:\python64\lib\os.pyc
import errno # builtin
import nt # builtin
# d:\python64\lib\ntpath.pyc matches d:\python64\lib\ntpath.py
import ntpath # precompiled from d:\python64\lib\ntpath.pyc
# d:\python64\lib\stat.pyc matches d:\python64\lib\stat.py
import stat # precompiled from d:\python64\lib\stat.pyc
# d:\python64\lib\genericpath.pyc matches d:\python64\lib\genericpath.py
import genericpath # precompiled from d:\python64\lib\genericpath.pyc
# d:\python64\lib\warnings.pyc matches d:\python64\lib\warnings.py
import warnings # precompiled from d:\python64\lib\warnings.pyc
# d:\python64\lib\linecache.pyc matches d:\python64\lib\linecache.py
import linecache # precompiled from d:\python64\lib\linecache.pyc
# d:\python64\lib\types.pyc matches d:\python64\lib\types.py
import types # precompiled from d:\python64\lib\types.pyc
# d:\python64\lib\UserDict.pyc matches d:\python64\lib\UserDict.py
import UserDict # precompiled from d:\python64\lib\UserDict.pyc
# d:\python64\lib\_abcoll.pyc matches d:\python64\lib\_abcoll.py
import _abcoll # precompiled from d:\python64\lib\_abcoll.pyc
# d:\python64\lib\abc.pyc matches d:\python64\lib\abc.py
import abc # precompiled from d:\python64\lib\abc.pyc
# d:\python64\lib\_weakrefset.pyc matches d:\python64\lib\_weakrefset.py
import _weakrefset # precompiled from d:\python64\lib\_weakrefset.pyc
import _weakref # builtin
# d:\python64\lib\copy_reg.pyc matches d:\python64\lib\copy_reg.py
import copy_reg # precompiled from d:\python64\lib\copy_reg.pyc
# d:\python64\lib\traceback.pyc matches d:\python64\lib\traceback.py
import traceback # precompiled from d:\python64\lib\traceback.pyc
# d:\python64\lib\sysconfig.pyc matches d:\python64\lib\sysconfig.py
import sysconfig # precompiled from d:\python64\lib\sysconfig.pyc
# d:\python64\lib\re.pyc matches d:\python64\lib\re.py
import re # precompiled from d:\python64\lib\re.pyc
# d:\python64\lib\sre_compile.pyc matches d:\python64\lib\sre_compile.py
import sre_compile # precompiled from d:\python64\lib\sre_compile.pyc
import _sre # builtin
# d:\python64\lib\sre_parse.pyc matches d:\python64\lib\sre_parse.py
import sre_parse # precompiled from d:\python64\lib\sre_parse.pyc
# d:\python64\lib\sre_constants.pyc matches d:\python64\lib\sre_constants.py
import sre_constants # precompiled from d:\python64\lib\sre_constants.pyc
# d:\python64\lib\locale.pyc matches d:\python64\lib\locale.py
import locale # precompiled from d:\python64\lib\locale.pyc
import encodings # directory d:\python64\lib\encodings
# d:\python64\lib\encodings\__init__.pyc matches d:\python64\lib\encodings\__init__.py
import encodings # precompiled from d:\python64\lib\encodings\__init__.pyc
# d:\python64\lib\codecs.pyc matches d:\python64\lib\codecs.py
import codecs # precompiled from d:\python64\lib\codecs.pyc
import _codecs # builtin
# d:\python64\lib\encodings\aliases.pyc matches d:\python64\lib\encodings\aliases.py
import encodings.aliases # precompiled from d:\python64\lib\encodings\aliases.pyc
import operator # builtin
# d:\python64\lib\functools.pyc matches d:\python64\lib\functools.py
import functools # precompiled from d:\python64\lib\functools.pyc
import _functools # builtin
import _locale # builtin
# d:\python64\lib\encodings\cp1252.pyc matches d:\python64\lib\encodings\cp1252.py
import encodings.cp1252 # precompiled from d:\python64\lib\encodings\cp1252.pyc
Python 2.7.3 (default, Apr 10 2012, 23:24:47) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
import time # builtin
import math # builtin
# D:\Documents\SP800-90B_EntropyAssessment-draft2\util90b.pyc matches D:\Documents\SP800-90B_EntropyAssessment-draft2\util90b.py
import util90b # precompiled from D:\Documents\SP800-90B_EntropyAssessment-draft2\util90b.pyc
# d:\python64\lib\argparse.pyc matches d:\python64\lib\argparse.py
import argparse # precompiled from d:\python64\lib\argparse.pyc
# d:\python64\lib\collections.pyc matches d:\python64\lib\collections.py
import collections # precompiled from d:\python64\lib\collections.pyc
import _collections # builtin
# d:\python64\lib\keyword.pyc matches d:\python64\lib\keyword.py
import keyword # precompiled from d:\python64\lib\keyword.pyc
# d:\python64\lib\heapq.pyc matches d:\python64\lib\heapq.py
import heapq # precompiled from d:\python64\lib\heapq.pyc
import itertools # builtin
# d:\python64\lib\bisect.pyc matches d:\python64\lib\bisect.py
import bisect # precompiled from d:\python64\lib\bisect.pyc
import _bisect # builtin
import _heapq # builtin
import thread # builtin
# d:\python64\lib\copy.pyc matches d:\python64\lib\copy.py
import copy # precompiled from d:\python64\lib\copy.pyc
# d:\python64\lib\weakref.pyc matches d:\python64\lib\weakref.py
import weakref # precompiled from d:\python64\lib\weakref.pyc
# d:\python64\lib\textwrap.pyc matches d:\python64\lib\textwrap.py
import textwrap # precompiled from d:\python64\lib\textwrap.pyc
# d:\python64\lib\string.pyc matches d:\python64\lib\string.py
import string # precompiled from d:\python64\lib\string.pyc
import strop # builtin
# d:\python64\lib\gettext.pyc matches d:\python64\lib\gettext.py
import gettext # precompiled from d:\python64\lib\gettext.pyc
# d:\python64\lib\struct.pyc matches d:\python64\lib\struct.py
import struct # precompiled from d:\python64\lib\struct.pyc
import _struct # builtin
# D:\Documents\SP800-90B_EntropyAssessment-draft2\mostCommonValue.pyc matches D:\Documents\SP800-90B_EntropyAssessment-draft2\mostCommonValue.py
import mostCommonValue # precompiled from D:\Documents\SP800-90B_EntropyAssessment-draft2\mostCommonValue.pyc
reading 1000000 bytes of data
Passed the restart tests
*** Final entropy estimate: 5.768830
# clear __builtin__._
# clear sys.path
# clear sys.argv
# clear sys.ps1
# clear sys.ps2
# clear sys.exitfunc
# clear sys.exc_type
# clear sys.exc_value
# clear sys.exc_traceback
# clear sys.last_type
# clear sys.last_value
# clear sys.last_traceback
# clear sys.path_hooks
# clear sys.path_importer_cache
# clear sys.meta_path
# clear sys.flags
# clear sys.float_info
# restore sys.stdin
# restore sys.stdout
# restore sys.stderr
# cleanup __main__
# cleanup[1] _collections
# cleanup[1] site
# cleanup[1] sysconfig
# cleanup[1] mostCommonValue
# cleanup[1] _heapq
# cleanup[1] abc
# cleanup[1] _bisect
# cleanup[1] strop
# cleanup[1] _weakrefset
# cleanup[1] gettext
# cleanup[1] sre_constants
# cleanup[1] util90b
# cleanup[1] _codecs
# cleanup[1] _struct
# cleanup[1] nt
# cleanup[1] _warnings
# cleanup[1] math
# cleanup[1] zipimport
# cleanup[1] struct
# cleanup[1] _functools
# cleanup[1] argparse
# cleanup[1] _locale
# cleanup[1] thread
# cleanup[1] keyword
# cleanup[1] signal
# cleanup[1] traceback
# cleanup[1] itertools
# cleanup[1] time
# cleanup[1] exceptions
# cleanup[1] _weakref
# cleanup[1] locale
# cleanup[1] functools
# cleanup[1] encodings
# cleanup[1] operator
# cleanup[1] collections
# cleanup[1] textwrap
# cleanup[1] encodings.cp1252
# cleanup[1] codecs
# cleanup[1] copy
# cleanup[1] weakref
# cleanup[1] encodings.aliases
# cleanup[1] heapq
# cleanup[1] string
# cleanup[1] bisect
# cleanup[1] re
# cleanup[1] sre_compile
# cleanup[1] _sre
# cleanup[1] sre_parse
# cleanup[2] copy_reg
# cleanup[2] types
# cleanup[2] errno
# cleanup[2] _abcoll
# cleanup[2] ntpath
# cleanup[2] genericpath
# cleanup[2] stat
# cleanup[2] warnings
# cleanup[2] UserDict
# cleanup[2] os.path
# cleanup[2] linecache
# cleanup[2] os
# cleanup sys
# cleanup __builtin__
# cleanup ints: 22 unfreed ints
# cleanup floats: 1 unfreed float

**Comment by msp79** [comment]
Hi, I ran the restart tests now with H_I = 5.76883... I got a bunch of logs below not given in the user guide pdf... I didn't see any issue though... It says Passed the restart tests... Could you please confirm if this is fine?

D:\Documents\SP800-90B_EntropyAssessment-draft2>d:\python64\python.exe -v restart.py jdirandbytes.bin 8 5.76883

D:\Documents\SP800-90B_EntropyAssessment-draft2>d:\python64\python.exe -v restart.py jdirandbytes.bin 8 5.76883
#installing zipimport hook
import zipimport #builtin
#installed zipimport hook
#d:\python64\lib\site.pyc matches d:\python64\lib\site.py
import site #precompiled from d:\python64\lib\site.pyc
#d:\python64\lib\os.pyc matches d:\python64\lib\os.py
import os #precompiled from d:\python64\lib\os.pyc
import errno #builtin
import nt #builtin
#d:\python64\lib\ntpath.pyc matches d:\python64\lib\ntpath.py
import ntpath #precompiled from d:\python64\lib\ntpath.pyc
#d:\python64\lib\stat.pyc matches d:\python64\lib\stat.py
import stat #precompiled from d:\python64\lib\stat.pyc
#d:\python64\lib\genericpath.pyc matches d:\python64\lib\genericpath.py
import genericpath #precompiled from d:\python64\lib\genericpath.pyc
#d:\python64\lib\warnings.pyc matches d:\python64\lib\warnings.py
import warnings #precompiled from d:\python64\lib\warnings.pyc
#d:\python64\lib\linecache.pyc matches d:\python64\lib\linecache.py
import linecache #precompiled from d:\python64\lib\linecache.pyc
#d:\python64\lib\types.pyc matches d:\python64\lib\types.py
import types #precompiled from d:\python64\lib\types.pyc
#d:\python64\lib\UserDict.pyc matches d:\python64\lib\UserDict.py
import UserDict #precompiled from d:\python64\lib\UserDict.pyc
#d:\python64\lib\_abcoll.pyc matches d:\python64\lib\_abcoll.py
import _abcoll #precompiled from d:\python64\lib\_abcoll.pyc
#d:\python64\lib\abc.pyc matches d:\python64\lib\abc.py
import abc #precompiled from d:\python64\lib\abc.pyc
#d:\python64\lib\_weakrefset.pyc matches d:\python64\lib\_weakrefset.py
import _weakrefset #precompiled from d:\python64\lib\_weakrefset.pyc
import _weakref #builtin
#d:\python64\lib\copy_reg.pyc matches d:\python64\lib\copy_reg.py
import copy_reg #precompiled from d:\python64\lib\copy_reg.pyc
#d:\python64\lib\traceback.pyc matches d:\python64\lib\traceback.py
import traceback #precompiled from d:\python64\lib\traceback.pyc
#d:\python64\lib\sysconfig.pyc matches d:\python64\lib\sysconfig.py
import sysconfig #precompiled from d:\python64\lib\sysconfig.pyc
#d:\python64\lib\re.pyc matches d:\python64\lib\re.py
import re #precompiled from d:\python64\lib\re.pyc
#d:\python64\lib\sre_compile.pyc matches d:\python64\lib\sre_compile.py
import sre_compile #precompiled from d:\python64\lib\sre_compile.pyc
import _sre #builtin
#d:\python64\lib\sre_parse.pyc matches d:\python64\lib\sre_parse.py
import sre_parse #precompiled from d:\python64\lib\sre_parse.pyc
#d:\python64\lib\sre_constants.pyc matches d:\python64\lib\sre_constants.py
import sre_constants #precompiled from d:\python64\lib\sre_constants.pyc
#d:\python64\lib\locale.pyc matches d:\python64\lib\locale.py
import locale #precompiled from d:\python64\lib\locale.pyc
import encodings #directory d:\python64\lib\encodings
#d:\python64\lib\encodings\__init__.pyc matches d:\python64\lib\encodings\__init__.py
import encodings #precompiled from d:\python64\lib\encodings\__init__.pyc
#d:\python64\lib\codecs.pyc matches d:\python64\lib\codecs.py
import codecs #precompiled from d:\python64\lib\codecs.pyc
import _codecs #builtin
#d:\python64\lib\encodings\aliases.pyc matches d:\python64\lib\encodings\aliases.py
import encodings.aliases #precompiled from d:\python64\lib\encodings\aliases.pyc
import operator #builtin
#d:\python64\lib\functools.pyc matches d:\python64\lib\functools.py
import functools #precompiled from d:\python64\lib\functools.pyc
import _functools #builtin
import _locale #builtin
#d:\python64\lib\encodings\cp1252.pyc matches d:\python64\lib\encodings\cp1252.py
import encodings.cp1252 #precompiled from d:\python64\lib\encodings\cp1252.pyc
Python 2.7.3 (default, Apr 10 2012, 23:24:47) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
import time #builtin
import math #builtin
#D:\Documents\SP800-90B_EntropyAssessment-draft2\util90b.pyc matches D:\Documents\SP800-90B_EntropyAssessment-draft2\util90b.py
import util90b #precompiled from D:\Documents\SP800-90B_EntropyAssessment-draft2\util90b.pyc
#d:\python64\lib\argparse.pyc matches d:\python64\lib\argparse.py
import argparse #precompiled from d:\python64\lib\argparse.pyc
#d:\python64\lib\collections.pyc matches d:\python64\lib\collections.py
import collections #precompiled from d:\python64\lib\collections.pyc
import _collections #builtin
#d:\python64\lib\keyword.pyc matches d:\python64\lib\keyword.py
import keyword #precompiled from d:\python64\lib\keyword.pyc
#d:\python64\lib\heapq.pyc matches d:\python64\lib\heapq.py
import heapq #precompiled from d:\python64\lib\heapq.pyc
import itertools #builtin
#d:\python64\lib\bisect.pyc matches d:\python64\lib\bisect.py
import bisect #precompiled from d:\python64\lib\bisect.pyc
import _bisect #builtin
import _heapq #builtin
import thread #builtin
#d:\python64\lib\copy.pyc matches d:\python64\lib\copy.py
import copy #precompiled from d:\python64\lib\copy.pyc
#d:\python64\lib\weakref.pyc matches d:\python64\lib\weakref.py
import weakref #precompiled from d:\python64\lib\weakref.pyc
#d:\python64\lib\textwrap.pyc matches d:\python64\lib\textwrap.py
import textwrap #precompiled from d:\python64\lib\textwrap.pyc
#d:\python64\lib\string.pyc matches d:\python64\lib\string.py
import string #precompiled from d:\python64\lib\string.pyc
import strop #builtin
#d:\python64\lib\gettext.pyc matches d:\python64\lib\gettext.py
import gettext #precompiled from d:\python64\lib\gettext.pyc
#d:\python64\lib\struct.pyc matches d:\python64\lib\struct.py
import struct #precompiled from d:\python64\lib\struct.pyc
import _struct #builtin
#D:\Documents\SP800-90B_EntropyAssessment-draft2\mostCommonValue.pyc matches D:\Documents\SP800-90B_EntropyAssessment-draft2\mostCommonValue.py
import mostCommonValue #precompiled from D:\Documents\SP800-90B_EntropyAssessment-draft2\mostCommonValue.pyc
reading 1000000 bytes of data
Passed the restart tests
*** Final entropy estimate: 5.768830
#clear __builtin__._
#clear sys.path
#clear sys.argv
#clear sys.ps1
#clear sys.ps2
#clear sys.exitfunc
#clear sys.exc_type
#clear sys.exc_value
#clear sys.exc_traceback
#clear sys.last_type
#clear sys.last_value
#clear sys.last_traceback
#clear sys.path_hooks
#clear sys.path_importer_cache
#clear sys.meta_path
#clear sys.flags
#clear sys.float_info
#restore sys.stdin
#restore sys.stdout
#restore sys.stderr
#cleanup __main__
#cleanup[1] _collections
#cleanup[1] site
#cleanup[1] sysconfig
#cleanup[1] mostCommonValue
#cleanup[1] _heapq
#cleanup[1] abc
#cleanup[1] _bisect
#cleanup[1] strop
#cleanup[1] _weakrefset
#cleanup[1] gettext
#cleanup[1] sre_constants
#cleanup[1] util90b
#cleanup[1] _codecs
#cleanup[1] _struct
#cleanup[1] nt
#cleanup[1] _warnings
#cleanup[1] math
#cleanup[1] zipimport
#cleanup[1] struct
#cleanup[1] _functools
#cleanup[1] argparse
#cleanup[1] _locale
#cleanup[1] thread
#cleanup[1] keyword
#cleanup[1] signal
#cleanup[1] traceback
#cleanup[1] itertools
#cleanup[1] time
#cleanup[1] exceptions
#cleanup[1] _weakref
#cleanup[1] locale
#cleanup[1] functools
#cleanup[1] encodings
#cleanup[1] operator
#cleanup[1] collections
#cleanup[1] textwrap
#cleanup[1] encodings.cp1252
#cleanup[1] codecs
#cleanup[1] copy
#cleanup[1] weakref
#cleanup[1] encodings.aliases
#cleanup[1] heapq
#cleanup[1] string
#cleanup[1] bisect
#cleanup[1] re
#cleanup[1] sre_compile
#cleanup[1] _sre
#cleanup[1] sre_parse
#cleanup[2] copy_reg
#cleanup[2] types
#cleanup[2] errno
#cleanup[2] _abcoll
#cleanup[2] ntpath
#cleanup[2] genericpath
#cleanup[2] stat
#cleanup[2] warnings
#cleanup[2] UserDict
#cleanup[2] os.path
#cleanup[2] linecache
#cleanup[2] os
#cleanup sys
#cleanup __builtin__
#cleanup ints: 22 unfreed ints
#cleanup floats: 1 unfreed float

**Comment by kerrymckay** [comment]
The verbose flag is in the wrong position -- it should come after the script name. Try it with "python.exe  restart.py -v jdirandbytes.bin 8 5.76883". When the -v flag is placed before the .py filename, it will print out all of that information regarding the python run.

**Comment by msp79** [comment]
Thanks a lot. It resolved the issue.
