### ISSUE TITLE
What are the main differences between versions 1.5 and 1.4

### ISSUE THREAD

**Issue by MenolGone** [usnistgov/SP800-90B_EntropyAssessment#208]
my system is centos 7.6 and I followed the steps from the wiki to install it ，but the 1.4 version can run smoothly, and the 1.5 version will prompt "double free or corruption" no matter whether it is tested with iid or non_iid ... so what are the main differences between versions 1.5 and 1.4

**Comment by joshuaehill** [comment]
1.1.5 should be downloaded as a [release](https://github.com/usnistgov/SP800-90B_EntropyAssessment/releases/tag/v1.1.5). Based on your error, I suspect that you are downloading the master branch, not a release.

The current master branch has a few problems that are addressed in PR #204. If you want to use the master branch, you are going to need to apply that PR.

**Comment by MenolGone** [comment]
I download the release version and it works , thanks a lot !

**Comment by joshuaehill** [comment]
If you issue has been addressed, could you please close it?
