### ISSUE TITLE
ea_restart: validity test failure?

### ISSUE THREAD

**Issue by smuellerDD** [usnistgov/SP800-90B_EntropyAssessment#233]
I have the following data for a reboot test calculated by ea_restart:
```
H_r: 2.805795
H_c: 6.959127
H_I: 1.000000

Validation Test Passed...

min(H_r, H_c, H_I): 1.000000
```

I am wondering why the test is flagged as "Validation Test Passed"? SP800-90B states in section 3.1.4.2:

 The entropy estimates from the row and the column datasets are expected to be close to the initial entropy estimate H I. If the minimum of Hr and Hc is less than half of H I, the validation fails, and no entropy estimate is awarded. 

H_r is significantly less than half of H_c - shouldn't the test fail?

**Comment by joshuaehill** [comment]
I don't understand why you think this ought to fail. H_I is the input entropy level. Half of H_I is 0.5 in your example, and both H_r and H_c are larger than that, so this should pass (not fail).

**Comment by joshuaehill** [comment]
Note that there is no comparison between `H_r` and `H_c/2` (or vise versa). The failure criteria is essentially a statement like
```
If min(H_r, H_c) < H_I/2 then fail.
```

**Comment by smuellerDD** [comment]
Agreed, sorry for the noise

**Comment by joshuaehill** [comment]
No worries!
