### ISSUE TITLE
TypeError: unorderable types: dict() > int()

### ISSUE THREAD

**Issue by LaszloHars** [usnistgov/SP800-90B_EntropyAssessment#3]
Win-7 (64 bit)
Python 3.5.1 |Anaconda 4.0.0 (64-bit)| (default, Feb 16 2016, 09:49:46) [MSC v.1900 64 bit (AMD64)] on win32
--- ---
C:\SP800-90B_Entropy>python noniid_main.py -v truerand_1bit.bin 1
reading 1000000 bytes of data
Read in file truerand_1bit.bin, 1000000 bytes long.
Dataset: 1000000 1-bit symbols, 2 symbols in alphabet.
Output symbol values: min = 0, max = 1
... ...
Traceback (most recent call last):
  File "noniid_main.py", line 142, in <module>
    pmax, minH = LZ78Y(dataset, verbose)
  File "C:\SP800-90B_Entropy\SP90Bv2_predictors.py", line 388, in LZ78Y
    if D.get(prev,0) > 0:
TypeError: unorderable types: dict() > int()
--- ---
I added a print command just before line 388:
       print(D.get(prev,0))
It gave the following output, before the error occurred:
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
{1: 1}
--- ---
32 times D.get(prev,0) is the number 0, then it becomes a dictionary, with one entry.
I guess, earlier Python versions did not catch the error.
Maybe the following helps: assign initially the empty dictionary to D.get(prev,0) and change the comparison to
         if len(D.get(prev,0)) > 0:

**Comment by LaszloHars** [comment]
Without finding the root cause of the problem, I patched the code in file SP90Bv2_predictors.py, to cure the symptoms. Replaced line 388 with the following two:
```
            Dg = D.get(prev,0)
            if (type(Dg)==int and Dg > 0) or (type(Dg)==dict and len(Dg) > 0):

```
The tests now complete without error messages. I hope that at some point the authors fix the problem.

**Comment by kerrymckay** [comment]
Sorry for the delay in addressing this. Please try the updated code with your version of python, and let me know if you still encounter errors.

**Comment by LaszloHars** [comment]
The updated code runs without errors (7/11/2016, 11:30AM PST). Thanks!
