### ISSUE TITLE
NIST SP 800-90

### ISSUE THREAD

**Issue by pgporada** [usnistgov/SP800-90B_EntropyAssessment#30]
Are there plans to bring [NIST SP 800-90A ](http://csrc.nist.gov/publications/PubsSPs.html#800-90A) and [NIST SP 800-90C](http://csrc.nist.gov/publications/PubsSPs.html#800-90C) to Github? Is it safe to assume that the SP 800-90A and SP 800-90C listed above are the latest published versions of those documents?

**Comment by joshuaehill** [comment]
The main site for NIST **draft** special publications is [here](http://csrc.nist.gov/publications/PubsDrafts.html). The main site for NIST special publications is [here](http://csrc.nist.gov/publications/PubsSPs.html).

The most recent versions that I'm aware of are the early 2016 drafts which you are pointing to, though I understand that NIST intends to release an updated document soon.

**Comment by pgporada** [comment]
Thanks!
