### ISSUE TITLE
noniid_main.py Memory leak?

### ISSUE THREAD

**Issue by AlanGornall** [usnistgov/SP800-90B_EntropyAssessment#31]
I have tried running the noniid_main.py script against an entropy sample in verbose mode. All goes well until it grinds to a halt at 19% through the MultiMMC Prediction Estimate where it slowly uses all of the memory in the system.

I am using Windows XP and  Python34 for the test. The entropy sample file is 1MB.

Any ideas?

**Comment by joshuaehill** [comment]
That's not a memory leak, that the test consuming mind boggling amounts of memory. The test (as specified, see the current draft of SP800-90B 6.3.9) is very very memory intensive. For the number of samples you are using (1 million samples, presumably), something in the order of 8-16GB should be sufficient. (It's difficult to give you an exact amount necessary, as it is data-set dependent.) One option that I've found useful is the Amazon EC2 r4 instances.

**Comment by AlanGornall** [comment]
Thank you Joshua. 

 

The most RAM that I have on a PC is 8GB and that still failed, so I am going to procure a new PC with 16GB. I am due an upgrade in any case. I am unfamiliar with renting space on a server farm and how easy this would be to use to conduct tests, so would rather stay away from the cloud if I can, but you have fuelled my curiosity as to what may be possible.

 

I have managed to run the iid_main.py scripts and these worked OK. However, when I run the restart test with the H_I value being the output of the IID test as detailed, I get a failure.

 

This is a bit of a pain, given how much work it is to put the restart sample set together. However, if I drop the H_I from the output value of 7.89262 to 7.85, then the restart test passes. Is there any tolerance allowed on the H_I value, Our samples do have some variation in them, and test to a range of values from about 7.86 bits per byte up to 7.9 bits per byte.

 

Any insight would be appreciated.

 

Regards,

 

Alan

**Comment by AlanGornall** [comment]
Hello again.

 

I am not so sure.

 

I built a new machine with 32GB memory on a Windows 7 platform with python 3.6.1 and got exactly the same error as I did when running on Windows 7 with 8GB RAM on Python 3.4.0. Memory usage peaked at 3.82GB and then the script seemed to stop and then crash after about twenty seconds. Our sample is 1MB. Error is as follows:

 

Computing MultiMMC Prediction Estimate: 58 percent completeTraceback (most recen

t call last):

  File "noniid_main.py", line 135, in <module>

    pmax, minH = MultiMMC(dataset, verbose)

  File "C:\Temp\SP90Bv2_predictors.py", line 292, in MultiMMC

  File "C:\Users\Alan Gornall\AppData\Local\Programs\Python\Python36-32\lib\coll

ections\__init__.py", line 537, in __init__

MemoryError

 

Has this script been tested on Windows? Should I run it on Linux instead?

 

Is there a specific version of Python that is known to work?

 

I can provide one of our samples if that would be useful.

 

Regards,

 

Alan

**Comment by msp79** [comment]
Try once using Python 64 bit version if not already done.

-Mahendra

**Comment by AlanGornall** [comment]
Thank you Mahendra

 

You are brilliant. I was not aware that I was using a 32-bit version of Python, but of course I was and so the program could only address 4GB of memory.

 

The test now works, and I have a new (unnecessary) high-performance workstation J

 

I think that some extra guidance needs to be added to these scripts indicating that 64-bit python is required and that there is a big memory requirement for the MMC tests.

 

Kind regards,

 

Alan

**Comment by msp79** [comment]
Hi Alan,

Good to know it helped.

A similar error was already logged by me. Thats why it was documented later
in the requirements as below.
Requirements

This code package requires 64-bit Python 2.7 or Python 3.

Learning for all of us: Its good to check the past closed issues as well to
save time :)

Thanks

Mahendra

**Comment by AlanGornall** [comment]
You are correct. I really did think that I was using the 64-bit version. My own fault.
