### ISSUE TITLE
LRS estimate takes a lot of time?

### ISSUE THREAD

**Issue by shashankv02** [usnistgov/SP800-90B_EntropyAssessment#32]
When I run the tool on my data sample, it gets stuck after t-Tuple estimate. It stays there for days. What could be the reason? Sample size is 2MB. 

(entropy) bash$ python noniid_main.py -v live-sample.entropy 8
reading 2512592 bytes of data
Read in file live-sample.entropy, 2512592 bytes long.
Dataset: 2512592 8-bit symbols, 256 symbols in alphabet.
Output symbol values: min = 0, max = 255

Running entropic statistic estimates:
- Most Common Value Estimate: p(max) = 0.240778, min-entropy = 2.05422
- Collision Estimate: p(max) = 0.255149, min-entropy = 1.97059
- Markov Estimate (map 6 bits): p(max) = 7.53176e-33, min-entropy = 0.833677
- Compression Estimate: p(max) = 0.520394, min-entropy = 0.942325
- t-Tuple Estimate: p(max) = 0.74758, min-entropy = 0.4197

**Comment by msp79** [comment]
Make sure to use 64 bit python version to rule out any first level issues.

Thanks
Mahendra

**Comment by kerrymckay** [comment]
Also, try reducing the sample sequence to 1,000,000 outputs.
