### ISSUE TITLE
Is it possible to run tests individually?

### ISSUE THREAD

**Issue by mslpensec** [usnistgov/SP800-90B_EntropyAssessment#42]
I noticed a recommendation in #9 that the user run "the LRS estimate with its verbose flag set to True to get more information." Is it possible to run tests individually? When I have tried to do this, the programs have not run. I was under the impression that noniid-main.py must be run first to do initial processing of the data.

When I try to run an individual test using the same syntax as the main program, for instance:
>LRS.py -v truerand_1bit.bin 1

The command prompt flashes briefly and nothing happens. Is there a different way to extract additional information from individual tests?

**Comment by shashankv02** [comment]
One way is to comment out the remaining test calls in noniid_main.py to run only LRS estimate.
