### ISSUE TITLE
Update for final version of SP 800-90B

### ISSUE THREAD

**Issue by mclearn** [usnistgov/SP800-90B_EntropyAssessment#43]
Are there plans to update this project to bring it in line with the changes from the final version of the SP?

**Comment by mslpensec** [comment]
I noticed in the readme.md it says "After SP 800-90B is finalized, the code will be ported to another language and performance improvements will be made."

Will the final version be hosted here, in a different github repository, or through another source?

Is there guidance for how to proceed with entropy assessment during the transition before the final version of the tool is released?

Thank you.

**Comment by joshuaehill** [comment]
Most of the statistical testing changes are fairly modest, so modification of the python reference implementation should be fairly straight forward. I would guess that the changes are working through their way through the NIST review process prior to release.

**Comment by kerrymckay** [comment]
Responsibility for the code is changing hands. This python implementation was provided to assist the development process, but is not production code for use in validation. The validation testing group will decide what will happen next. There is a lag (typically 6 months to a year, I believe) between when a Special Publication is released and when testing begins. I will try to follow this and let folks know when (and how) another version is available.

I'd also like to say thank you to everyone for your feedback on the document, tests, and this reference code. Your contributions were extremely valuable and greatly appreciated. Thank you!

**Comment by celic** [comment]
Hi all,

My name is Chris Celi, I'll be the primary point of contact for this code for now. We are working on an updated C++ implementation. It will be hosted in this same repository. I'll be going through the issues and pull requests to see if they are relevant to the new implementation.

If you have any questions or concerns feel free to raise issues here.

Thanks,
Chris Celi
