### ISSUE TITLE
Longest subsequences

### ISSUE THREAD

**Issue by paulidale** [usnistgov/SP800-90B_EntropyAssessment#44]
The `README.md` mentions the possibility of speeding up the longest repeated sub-string method.
The approached I used was to computed the suffix array for the data which can be done in linear O(n) time.  From this the longest common prefix array (LCP) can be computed, again in linear time.

Look for the paper by _Ge Nong_, _Sen Zhang_ and _Wai Hong Chan_:
> Two Efficient Algorithms for Linear Suffix Array Construction 2008

The LCP finds the longest repeated sub-string and the most common tuples very efficiently.

**Comment by paulidale** [comment]
I managed O(n . v) for the t-tuple test, where n is the number of data points and v is the length of the longest common tuple.  My implementation of the LRS estimate has the same complexity.  I do have notes against both that _there ought to be a more efficient method_.  Just using the LCP was enough of a win for my purposes.

I used the SA implementation from the paper I referenced, it seems fast enough.  To the extent I didn't bother caching the result, I just recalculate the SA/LCP each time it was needed.

**Comment by celic** [comment]
Hi, we are in the process of shifting the Python code to C++ code in sync with the final released standard. I recall looking at this test specifically and looking at suffix tree/array implementations to see how they would fit. I believe I did end up with a slightly modified suffix array implementation but I don't fully remember (this was 2 years ago). Feel free to look at the cpp directory and look through the LRS code. 

If you have concrete suggestions on improvements or implementations (in addition to the paper), feel free to either make a pull request or add information here.

**Comment by joshuaehill** [comment]
I've spent some time thinking about both the t-tuple and LRS test using the LCP array. At present, I think that my implementation occurs using work factor O(L * max(t,(v-u+1))) in order to conduct both tests. If anyone has a suggestion on doing better than this, I'm surely interested.

I've attached a test case that triggers significantly degraded behavior.

[LRS-testcase.zip](https://github.com/usnistgov/SP800-90B_EntropyAssessment/files/1924940/LRS-testcase.zip)

I looked at the existing NIST cpp implementation, and barring some really fancy Standard Template Library implementation, it doesn't seem to make use of a suffix array / LCP.

**Comment by joshuaehill** [comment]
This is comically delayed, but I'd be interested in feedback from @paulidale on the current state of affairs for these tests with the current NIST tool.

I wrote up an algorithm which used the longest common prefix (LCP) array (which I calculated from the Suffix Array) to perform these tests in [the last few pages of our public SP800-90B implementation comments to NIST](http://www.untruth.org/~josh/sp80090b/NIST.SP.800-90B%20implementation%20comments%2020181015.pdf).

I also implemented this approach in one of my pull requests that were accepted by NIST, so this approach is the one used by the current mainline NIST 90B tool within the "lrs_test.h" file.

I'd be really interested in any comments that you might have. In particular, this runs in O(v*L) (where v is the length of the longest repeated string, and L is the data length in symbols) to accomplish both the entire t-tuple and LRS test.

I also developed a one pass algorithm, but it was opaque, and didn't actually perform much faster than this nice approach.

**Comment by paulidale** [comment]
@joshuaehill my implementation has the same complexity as yours O(v*L).  I didn't bother doing the tests simultaneously, running each independently isn't a big time cost either way and makes for more modular code.

I do have a comment in the _find the frequency of the most common tuple of each length_ function: 
> There should be a more efficient method possible

I've not had time to think about this further.  My guess would be that a single pass algorithm isn't going to be a big win unless _v_ gets very large and in that case, I suspect that, other tests are going to notice.  E.g. an input of all '1's hits the worst case.
