### ISSUE TITLE
Possible performance gain in permutation tests

### ISSUE THREAD

**Issue by paulidale** [usnistgov/SP800-90B_EntropyAssessment#46]
Modifying the permutation tests so that a specific test ceases to be run once five values are in the mid-range i.e. in the open interval (5, PERMS-5) provides a very significant speed up.  The loss is the exact value of the statistic, however failures, either high or low, are still detected correctly.

This change will provide significantly more performance gain than the change to multi-threading did.  It also avoids race conditions in calling _rand_ and the seeding issue in #45

**Comment by joshuaehill** [comment]
This approach was discussed in some detail within pull request #41 . You may want to look at the comments to that pull request, where the amount of speedup is characterized.

**Comment by paulidale** [comment]
Thanks for the pull request reference.  Both stopping early and stopping individual tests early are performance improvements but, as noted, with some loss of information in the pass case.

Something I didn't investigate is if some information could be gleaned from the number of iterations required before a test couldn't fail.  e.g. a test that _can't fail_ after 40 iterations versus one that takes 4000.  Under the IID assumption, it seems like this might follow a negative binomial distribution or something similar.  This is just a guess, I've not tried a theoretical approach to this.

I'll close this issue as redundant.  Thanks again.
