### ISSUE TITLE
User Guide

### ISSUE THREAD

**Issue by rt5v3y02fk** [usnistgov/SP800-90B_EntropyAssessment#47]
In the User Guide, you do not give the command to dump the raw entropy data to a binary file.  I use the following command.  Is this correct?

In order to get the entropy data, you need to run the following linux command or similar command to dump the entropy from /dev/urandom.
    #dd if=/dev/urandom of=/dev/null bs=1M count=1

Since the random data in /dev/[u]random, has been compressed, is it still valid to test against?  If not please add the correct command to the User Guide.

**Comment by joshuaehill** [comment]
These tools are intended to be used with the raw data, prior to any conditioning (please see SP800-90B for details!)

The data from /dev/urandom is extensively conditioned, so it is not appropriate to use these tools on the output of /dev/urandom.

Extracting the raw data from whatever unix variant you are using likely requires significant (implementation specific!) effort, so it's not really appropriate to include this style of detail in the user guide.
