### ISSUE TITLE
Incorrect padding in certain case of conversion2 in permutation tests

### ISSUE THREAD

**Issue by celic** [usnistgov/SP800-90B_EntropyAssessment#6]
In the `conversion2` method inside `permutation_tests.py`, there is a corner case that is mishandled. When the length of the dataset is a multiple of 8, an extra block of 0's is added to the end of the data instead of just having no padding at all.

Specifically, 

    8 - len(s) % 8

becomes 8 when `len(s)` is a multiple of 8 (as `len(s) % 8 = 0`). All other cases operate as expected.

**Comment by LaszloHars** [comment]
how about adding a pair of parentheses to fix the issue?
`(8 - len(s)) % 8`

**Comment by LaszloHars** [comment]
The "bug fix" works, but ridiculously complex: 8 lines of code instead of removing the offending first "8" from the line in error.
