### ISSUE TITLE
Makefile seems very specific to the particular devolopment system used

### ISSUE THREAD

**Issue by joshuaehill** [usnistgov/SP800-90B_EntropyAssessment#68]
In particular, the various include directories in "INC" shouldn't be necessary (and indeed, cause problems on systems where the defaults are not those that are specified).

**Comment by celic** [comment]
Duplicate of #64? Perhaps that one can be closed in favor of this one.

**Comment by joshuaehill** [comment]
It's related, in that they are both Makefile issues. This one is mainly about the directories listed in the "INC" Makefile variable, which aren't appropriate for many (most?) other systems.
