### ISSUE TITLE
Incorrect results from 1 bit samples.

### ISSUE THREAD

**Issue by dj-on-github** [usnistgov/SP800-90B_EntropyAssessment#70]
[root@deadhat bin]# non_iid_main truerand_1bit.bin 1 -v
Opening file: truerand_1bit.bin

Running non-IID tests...

Entropic statistic estimates:
Most Common Value Estimate = 0.995043
Collision Test Estimate = **0.32116**
Markov Test Estimate = 0.998489
Compression Test Estimate = **0.0891459**

The collision and and compression tests run over the 1 bit uniform samples give extreme underestimates that disagree with my own implementation.

**Comment by dj-on-github** [comment]
For example, the compression result from my implementation, run over 1,000,000 uniform 1 bit symbols is ~0.76. The test is grossly underestimating entropy and the one implemented here is massively underestimating entropy.

This is delaying our ability to deliver test results for certification.

**Comment by dj-on-github** [comment]
I'm waiting while it churns through the tests. The MMC test managed to output entropy greater than one bit per bit.
MultiMMC Test: 100% complete
        Correct: 485179
        P_avg (global): 0.486467
        P_run (local): 0.408691
Multi Markov Model with Counting (MultiMMC) Prediction Test = 1.03958

**Comment by joshuaehill** [comment]
Could you supply the data file that you are using?

**Comment by dj-on-github** [comment]
I'm using truerand_1bit.bin from the repo.

**Comment by dj-on-github** [comment]
See the command line above..
# non_iid_main truerand_1bit.bin 1 -v

**Comment by joshuaehill** [comment]
If you apply my pull request, the results are:
`
Running Most Common Value Estimate...
        Most Common Value Estimate (bit string) = 0.995043 / 1 bit(s)

Running Entropic Statistic Estimates (bit strings only)...
        Collision Test Estimate (bit string) = 0.900936 / 1 bit(s)
        Markov Test Estimate (bit string) = 0.998486 / 1 bit(s)
        Compression Test Estimate (bit string) = 0.829677 / 1 bit(s)

Running Tuple Estimates...
        T-Tuple Test Estimate (bit string) = 0.914226 / 1 bit(s)
        LRS Test Estimate (bit string) = 0.985818 / 1 bit(s)

Running Predictor Estimates...
        Multi Most Common in Window (MultiMCW) Prediction Test Estimate (bit string) = 0.996972 / 1 bit(s)
        Lag Prediction Test Estimate (bit string) = 0.998292 / 1 bit(s)
        Multi Markov Model with Counting (MultiMMC) Prediction Test Estimate (bit string) = 0.996660 / 1 bit(s)
        LZ78Y Prediction Test Estimate (bit string) = 0.997050 / 1 bit(s)

H_original: 1.000000
H_bitstring: 0.829677

min(H_original, 1 X H_bitstring): 0.829677
`

These results are consistent with our tool.

**Comment by dj-on-github** [comment]
Ahh - they changed the name of the executable just to confuse me.
The results are still silly - running over data of about 0.95 min-entropy I get:

Running Entropic Statistic Estimates (bit strings only)...
         *** WARNING: binary search for collision test failed ***
        Collision Test Estimate (bit string) = 1.000000 / 1 bit(s)
        Markov Test Estimate (bit string) = 0.942422 / 1 bit(s)
        Compression Test Estimate (bit string) = **0.685077** / 1 bit(s)

Running Tuple Estimates...
        T-Tuple Test Estimate (bit string) = **0.033531** / 1 bit(s)

**Comment by joshuaehill** [comment]
You should take a look at my pull request. I think that should address most of the problems you are seeing.

**Comment by dj-on-github** [comment]
I pulled your versions. The collision is fixed, but the ttuple is still messed up over partially entropic data.

```
Opening file: 'rawdata_CID-RGY_PROC-ESOUTPUT_1p0V_-10p0C_.bin'
Number of Binary Symbols: 1000000

Symbol alphabet consists of 2 unique symbols

Running non-IID tests...

Running Most Common Value Estimate...
        Most Common Value Estimate (bit string) = 0.930593 / 1 bit(s)

Running Entropic Statistic Estimates (bit strings only)...
         *** WARNING: binary search for collision test failed ***
        Collision Test Estimate (bit string) = 1.000000 / 1 bit(s)
        Markov Test Estimate (bit string) = 0.942422 / 1 bit(s)
        Compression Test Estimate (bit string) = 0.685077 / 1 bit(s)

Running Tuple Estimates...
        T-Tuple Test Estimate (bit string) = **0.033531** / 1 bit(s)
```

The file is a series of 1,000,000  00 or 01 bytes.

If I use '-a' instead of '-t' the results are less messed up, with only the compression test underestimating.

```
# non_iid_main ../../../SP800-90B_EntropyAssessment/bin/truerand_1bit.bin 1 -i -a  -v
Opening file: '../../../SP800-90B_EntropyAssessment/bin/truerand_1bit.bin'
Number of Binary Symbols: 1000000

Symbol alphabet consists of 2 unique symbols

Running non-IID tests...

Running Most Common Value Estimate...
        Most Common Value Estimate (bit string) = 0.995043 / 1 bit(s)

Running Entropic Statistic Estimates (bit strings only)...
        Collision Test Estimate (bit string) = 0.900932 / 1 bit(s)
        Markov Test Estimate (bit string) = 0.998486 / 1 bit(s)
        Compression Test Estimate (bit string) = 0.729684 / 1 bit(s)

Running Tuple Estimates...
        T-Tuple Test Estimate (bit string) = 0.914226 / 1 bit(s)
        LRS Test Estimate (bit string) = 0.985818 / 1 bit(s)

Running Predictor Estimates...
        Multi Most Common in Window (MultiMCW) Prediction Test Estimate (bit string) = 0.996972 / 1 bit(s)
        Lag Prediction Test Estimate (bit string) = 0.998291 / 1 bit(s)
```
So it looks like a problem with the truncate option.

**Comment by joshuaehill** [comment]
I haven't done any testing using truncation, so that could well be quite broken. Could you provide the data for testing purposes?

**Comment by joshuaehill** [comment]
> Multi Markov Model with Counting (MultiMMC) Prediction Test = 1.03958

I'm baffled by this result, which shouldn't be possible for a 1-bit source. Did you figure out what caused this (obviously wrong) result?

**Comment by dj-on-github** [comment]
No. I have yet to dig into the source. I’m busy getting the report out.

**Comment by joshuaehill** [comment]
Wait, is that MultiMMC test result your tool's output, or output from the NIST tool? That output doesn't seem to correspond to either tool on github.

**Comment by dj-on-github** [comment]
That was the old version before NIST updated it. They changed the executable name, so I was executing the old executable after compiling the new one.

**Comment by joshuaehill** [comment]
Got it! That would be a bug in that implementation (that version likely neglects the 1/k term in the minimum).

**Comment by joshuaehill** [comment]
I just checked in a branch that includes all the computational fixes that I know about, and produces verbose outputs that are useful for debugging.

I'll make a pull request for this verbose output once the computational fixes get reviewed and integrated, but this may be useful for testing and comparison.

https://github.com/joshuaehill/SP800-90B_EntropyAssessment/tree/2018UL

**Comment by joshuaehill** [comment]
> It appears that truncation only happens when the symbols are greater than 1 bit wide. I have no idea why this should, but if you use single-bit data, the truncation flag is ignored (and the data is not truncated.)

I should have read the description more closely. The -t / -a flag applies _only_ to the calculation of H_bitstring (that is, the data used to calculate H_original data is never truncated, only the data used to generate H_bitstring is truncated.) This is also why truncation does not apply to binary sources: for such sources, there is no testing that produces H_bitstring.

**Comment by joshuaehill** [comment]
@dj-on-github Is this resolved at this point? I'm not presently seeing differences in the output between the corrected non_iid tests in the NIST tool (https://github.com/joshuaehill/SP800-90B_EntropyAssessment/tree/2018UL) and the UL tool. If you are still seeing strangeness, could you provide example data that seems to be poorly behaved?

**Comment by zsyahqy** [comment]
@joshuaehill 
Hi Could I ask a question？even from your posted test results，the collision and compression test results are too low for the other results. I find a paper saying these two tests are flawed. Could you please check whether these two tests are suitable? Here is the paper link https://tosc.iacr.org/index.php/ToSC/article/download/769/727/

**Comment by joshuaehill** [comment]
I've read that paper, and I'm not sure how broadly applicable their conclusions are. They analyze one specific sort of data source (they model a first order Markov process with two states) and then come to the conclusion that these two estimators underestimate the entropy of that type of source. That may be true, but fundamentally this conclusion only applies to that particular type of source, and there are many other types of sources that behave differently (for a few more examples, see our comments here: https://bit.ly/UL90BCOM). For other types of sources _all_ of the estimators _overestimate_ the available entropy.

The test set (or, really, any other such particular statistical test set) is an attempt to test for a specific class of statistical problems. Is this particular arrangement "the one true set of tests"? Certainly not! Conceptually, there are literally an infinite number of possible defects, and tests for each. Do the 90B estimators do a _mostly_ reasonable job on common noise sources? Sure.

For those two estimators (the compression and collision estimators), in particular, I encourage you to read the original Hagerty-Draper paper where these tests were originally specified (https://csrc.nist.gov/csrc/media/events/random-bit-generation-workshop-2012/documents/hagerty_entropy_paper.pdf); in that paper, it is clear that this entire construction approach is based on a set of somewhat quirky worst-case assumptions that will surely not be true for most sources, and so these estimators are expected to commonly underestimate the entropy.

Having said that, in this context somewhat underestimating the entropy isn't that big of a deal, whereas overestimating the entropy may be catastrophic. In our tests, we found that, on average, full entropy bit sources evaluate to about 0.85 bits per output bit. That's not great, but it's not all that terrible, either. The degree of under (or over) estimation varies by source and parameter, so it's all rather complicated.

I certainly haven't come to the conclusion that these estimators should be removed (and I am somewhat uncomfortable with the removal of the previous low-assessment producer for multi-bit sources, the Markov estimator).

**Comment by zsyahqy** [comment]
@joshuaehill Thanks for the Great work! That's for true that underestimation does no harms except for costing more data. And maybe the more estimators, the better!

**Comment by dj-on-github** [comment]
Yep. Thats a general result. Single input extractors need greater than 0.5
for a min entropy source. That paper led to the cbc-mac design we used and
led to its inclusion in 90B. Seth Terashima relaxed it a bit. But that came
later. I don’t know where nist got the equations that popped up in the
final version of 90B but they are contradicted by that paper.

**Comment by joshuaehill** [comment]
After watching [John Kelsey's COSIC talk](https://www.youtube.com/watch?v=6F_FW87fUvc), I think that I can back into the NIST calculations.

NIST looked for min-entropy reduction due to collision of a random map. They cite the bounds paper they use, which is Raab and Steger's ["Balls into Bins - A Simple and Tight Analysis"](http://www.dblab.ntua.gr/~gtsat/collection/scheduling/Balls%20into%20Bins%20A%20Simple%20and%20Tight%20Anal.pdf). This paper provides likely bounds for the maximum number of randomly distributed balls that end up in any particular urn (so, in this setting, the maximum number of pre-images of the random map that are likely to collide).

They operate under the assumption that the underlying distribution is the "near-uniform distribution" described by Hagerty-Draper (thus the way P_high and P_low are set in 90B 3.1.5.1.2 step 1). They assume that the post-conditioning maximal symbol is either due to the most likely input symbol together with an average number of less probable symbols (this case corresponds to psi in step 3), or a "maximal" number of the less probable symbols (omega in step 5).

This appears to be a heuristic argument based on a bunch of assumptions:
- the conditioning function is well modeled as a random map,
- the underlying input distribution is iid (so that entropy assessment through the probability of the "most probable symbol" makes sense),
- the "near-uniform distribution" constitutes a "worst case" in this situation,
- the asymptotic bounds from the Raab-Steger paper apply when using with the small parameters that are going to be encountered in practice, 
- only the two conditions that I outlines are likely to produce the most likely output symbol (why not the most probable input symbol together with a maximal collision, for instance?)

The above Dodis paper doesn't make _most_ of these assumptions, so it isn't surprising that their bounds aren't as pleasant.

**Comment by dj-on-github** [comment]
Yep. That’s what I was referring to as a ‘min entropy source’ that’s one
where you don’t make other assumptions about things like iid.

I’m not sure why you can’t make most probable symbol determinations for non
iid data. That’s exactly what Rachael Parker’s IVSW paper does - derives
the probability of the most probable symbol from a birth death markov model
of a metastable entropy source.

**Comment by joshuaehill** [comment]
Parker's paper had its own set of simplifying assumptions; first, it presumes a very specific way that state is kept (which is appropriate for the design described in that paper, but isn't true for all sources). Parker also broadened the notion of what a single symbol was is to be an M-bit output string, and then made a basically heuristic assumption that it's appropriate to average over both all possible starting input states, and across all bits in the M output bits.  This makes sense when attempting to characterize an average case, but this is different than characterizing the "worst-case" predictability of the output of the source on a per-bit basis. (As an aside, the assumptions and procedure in Parker are conceptually similar to the the Markov test in Hagerty-Draper.)

My point isn't to suggest that Parker's approach (or, indeed, NIST's approach) is wrong, but rather to point out that one can construct sources for which these assumptions don't hold, and when one makes stronger assumptions you can often get better looking answers than if you don't.

**Comment by joshuaehill** [comment]
I think that this issue should be closed at this point.
