### ISSUE TITLE
restart_main.cpp uses SIZE instead of MIN_SIZE

### ISSUE THREAD

**Issue by slaufmann** [usnistgov/SP800-90B_EntropyAssessment#74]
In some places in `restart_main.cpp` the constant `SIZE` is referenced but not defined which leads to a compilation error like this one:
```
restart_main.cpp: In function ‘int main(int, char**)’:
restart_main.cpp:105:16: error: ‘SIZE’ was not declared in this scope
  if(data.len > SIZE) data.len = SIZE;
                ^~~~
restart_main.cpp:105:16: note: suggested alternative: ‘FILE’
  if(data.len > SIZE) data.len = SIZE;
                ^~~~
                FILE
restart_main.cpp:107:16: error: ‘SIZE’ was not declared in this scope
  if(data.len < SIZE){
                ^~~~
restart_main.cpp:107:16: note: suggested alternative: ‘FILE’
  if(data.len < SIZE){
                ^~~~
                FILE
```
My guess is that this should be changed to `MIN_SIZE` as this is defined in the file `utils.h` and used in the implementation of iid and non_iid.

**Comment by joshuaehill** [comment]
Before you actually use restart testing, you should understand that the current test is more prone to failure than intended. See issue #56.
