### ISSUE TITLE
Dependencies for compilation

### ISSUE THREAD

**Issue by QuentinGouchet** [usnistgov/SP800-90B_EntropyAssessment#83]
Please describe how to compile on macOS and Linux, and what packages are necessary.
On CentOS 7, I have noticed that I needed at least bzip2-devel and libstdc++-devel, on top of gcc-c++, for the code to compile.

**Comment by joshuaehill** [comment]
This could be added to the README file. Presently, it says:

> This code package requires a C++11 compiler. GCC is preferred (and the only platform tested). There is one method that involves a GCC-only method (chi_square_tests.h -> binary_goodness_of_fit() -> __builtin_popcount()). To run this you will need GCC.

It would be a good ideal to mention the BZLIB dependency here.

The current Makefile creates binaries that are only compatible with Intel CPUs that support SSE2.

Long term, it would be a good idea to create a list of supported platforms, and then identify platform-specific ways to get the program compiled and working.

**Comment by locksmithone** [comment]
I followed suggestions in https://iscinumpy.gitlab.io/post/omp-on-high-sierra/.
Basically, I installed LLVM OpenMP with:

`brew install libomp`

And modified the first lines of the Makefile to include the necessary options. The first four lines of the Makefile thus become:

`CXX = g++
CXXFLAGS = -std=c++11 -Xpreprocessor -fopenmp -lomp #-fopenmp
CDDFLAGS = -std=c++11 -ggdb -Xpreprocessor -fopenmp -lomp #-fopenmp
TESTFLAGS = -ftree-vectorize -msse2 -Ofast`

Compilation was successful then.
