### ISSUE TITLE
Usage print out

### ISSUE THREAD

**Issue by QuentinGouchet** [usnistgov/SP800-90B_EntropyAssessment#84]
Usage shows:
printf("Usage is: ./non_iid_main <file_name> <bits_per_word> <-i|-c> <-a|-t> [-v]\n\n");
but the compiled binary is named ea_non_iid_main

**Comment by joshuaehill** [comment]
The term "rightmost" when applied to bits should probably be changed to "least significant" to reduce ambiguity. (Calling these the "rightmost bits" presumes a big endian ordering).
