### ISSUE TITLE
Compilation of restart_main

### ISSUE THREAD

**Issue by QuentinGouchet** [usnistgov/SP800-90B_EntropyAssessment#85]
$ make restart_main
g++ -std=c++11 -fopenmp    restart_main.cpp   -o restart_main
restart_main.cpp: In function ‘int main(int, char**)’:
restart_main.cpp:105:16: error: ‘SIZE’ was not declared in this scope
  if(data.len > SIZE) data.len = SIZE;
                ^
restart_main.cpp:107:16: error: ‘SIZE’ was not declared in this scope
  if(data.len < SIZE){ 
                ^
make: *** [restart_main] Error 1

**Comment by joshuaehill** [comment]
This is a duplicate issue. See issues #73 and #74.

**Comment by joshuaehill** [comment]
Also, before you actually use restart testing, you should understand that the current test is more prone to failure than intended. See issue #56.
