### ISSUE TITLE
There should be some "known answer test" style functionality

### ISSUE THREAD

**Issue by joshuaehill** [usnistgov/SP800-90B_EntropyAssessment#94]
This tool seems destined for use within the FIPS 140-2 program. In order to assure that any particular compiled instance of this tool is performing correctly, it would be a good idea to have a script that runs the program and checks the results against "known good" results.

To support this, we need both a program that automates comparison of results, along with some set of data that is, in some sense, representative of data that will ultimately be assessed by this tool (along with the expected results for this data).

**Comment by celic** [comment]
The `bin/` directory has some known files that can be used for this. I suppose all that's left is adding a script that runs the tool and compares it to the expected results. I know the IID tests use some randomness, so there's a strong chance to not get identical results, so that should be kept in mind.

**Comment by joshuaehill** [comment]
Indeed. All the permutation tests aren't expected to perform the same exact way between runs. One way to proceed there would be to make a mode that seeds the DRBG with a fixed value and disables all multi-threading (as otherwise the thread schedule ordering could cause variation in the results).

For the other tests, they're all completely deterministic.

As an aside, UL's internal tool has such self-testing functionality, and we've noted some result differences when our tool is compiled on different compiler versions / different compilers (e.g., gcc 6 vs 8, or gcc vs clang, etc.), due to the various compilers emitting nominally equivalent (slightly different) orderings of floating point calculations, resulting in different rates of accumulation of floating point errors. The reason that I mention this it is important that results be checked to see if they are "suitably close" rather than "identical", as (sadly) "identical" isn't always the expected result.
